### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by brandon-arnold** [google/googletest#1079]
Hello,

It looks like [master](https://github.com/google/googletest) is the only branch that builds on all systems for me, and not the most recent 1.8 release around 7 months ago. Is there plan to tag a new release any time soon?

-Brandon

**Comment by alpha-gj** [comment]
I want to know too. 
Thanks 

GJ

**Comment by 4brunu** [comment]
I'm also interested in this.
Maybe @BillyDonahue can help.
Thanks

**Comment by SylvainCorlay** [comment]
A `1.8.1` including the fix for mingw support (https://github.com/google/googletest/pull/721) which was merged right after the last release would be greatly appreciated.

**Comment by petko** [comment]
Please do something about it. Right now it's quite confusing for people not monitoring closely the development of GTest which commits are stable enough for production use. I use 1.8, but it references some TR1 items in the Standard Library and I started getting deprecation warnings in the latest compilers..

**Comment by madscientist** [comment]
If GTest decides to go to a "continuous release" model (or really, even if it doesn't) I really would love to see a NEWS file or similar updated in commits that add major new features, important bug fixes, etc. with a description.  The Git history doesn't really help: it's a long list of "merge pull request" commit messages, mostly without information about what was actually changed.

I really have no idea what changes I'm getting if I take a cut of the Git repository.

Thanks!

**Comment by gennadiycivil** [comment]
See https://github.com/google/googletest/issues/1366

**Comment by madscientist** [comment]
Thanks for the pointer!  I'm afraid I'm a little too slow today to grok it fully.  Are you saying that all the changes being made are related to C++11 support and no other changes to GTest are happening, so no NEWS-type file is necessary because there aren't any functional improvements (only rewrites to C++11)?

Or are you saying that the description of how GTest is going to be developed and released going forward is defined by the comment discussing Abseil compatibility policies in the second paragraph?

In either case I still think it would be a good practice to maintain a NEWS or CHANGES file.  It may currently have only one entry ("Convert GTest to C++11"), but it will give a good place to add information in the future.  If there are no more releases, there won't be release notes or whatever.  It's good if the documentation is up to date and we can always get the latest code (due to compatibility guarantees), but scanning the documentation to see what improvements might have been made since the last time we used GTest, that we can take advantage of, is not really feasible.

There is already a CHANGES file available, but it doesn't seem to have been updated since 1.7.0.

Also it would probably be helpful to users to update the front-facing README.md file with information on the release model using Abseil now, instead of having it stashed in a Git issue.

Thanks!

**Comment by gennadiycivil** [comment]
@madscientist Just a clarification

* There is on-going merging work that will result in 1.8.1 being produced. The 1.8.1 will be the last release that works with pre-C++11 compilers. The 1.8.1 will not accept any requests for any new features and any bugfix requests will only be accepted if proven "critical"

* After 1.8.1 is ready , the work will start to remove C++98 support / cleanup code in the master branch At some point when this work is completed there will be a 1.9.0 tagged release and after that googletest will follow [Abseil compatibility policies](https://abseil.io/about/compatibility). 

The question about NEWS file and CHANGES file is orthogonal to this process. 

HTH
G

**Comment by SylvainCorlay** [comment]
Many thanks @gennadiycivil for the update, and more generally for all the work on maintaining and pushing googletest forward.

**Comment by henryiii** [comment]
That's great, @gennadiycivil! Will the current changes in master go into 1.8.1 or 1.9.0?

**Comment by gennadiycivil** [comment]
@henryiii , the plan is for the current changes in master to eventually culminate in 1.8.1 . After that master becomes a subject to general cleanup and removal of old C++98 baggage which will result in 1.9.0.

**Comment by henryiii** [comment]
Thanks for the clarification, that would be great!

(PS: Not that it matters, but why not call that 1.9 and then make the C++11 only support version 2.0?)

**Comment by gennadiycivil** [comment]
Good point. We can do bikeshedding
<https://en.wiktionary.org/wiki/bikeshedding> on the name to our hearts
pleasure when ready.

**Comment by gennadiycivil** [comment]
Another update, time-wise. No promises but we anticipate making 1.8.1 release in the coming months. 
Hope this helps.

**Comment by zz-pony** [comment]
Thanks for working on a new release. I can't help asking, when will 1.8.1 become ready?

**Comment by m-tmatma** [comment]
Please don't release without fixing #1595(#1606).

**Comment by SylvainCorlay** [comment]
Any update on that front? People have been packaging at random commits on the master branch since no release was made in the past couple of years?

Why not just tagging a release?

**Comment by SylvainCorlay** [comment]
Is there any blocker for tagging `1.8.1` ?

**Comment by gennadiycivil** [comment]
Should be "really soon now", cant promise exact date.

**Comment by gennadiycivil** [comment]
https://github.com/google/googletest/releases/tag/release-1.8.1

**Comment by bilelzouari** [comment]
will there be a release for GTEST_SKIP() or not yet? thanks

**Comment by gennadiycivil** [comment]
Yes, - there will be a next release based on the current master.
https://github.com/google/googletest#future-plans

Thanks
G
