### ISSUE TITLE
Warnings with GCC 7.1

### ISSUE THREAD

**Issue by FireBurn** [google/googletest#1094]
I opened an issue https://github.com/KhronosGroup/SPIRV-Tools/issues/645 but they think the problem might be with googletest itself 

Scanning dependencies of target test_spirv_unit_tests
[ 22%] Building CXX object test/CMakeFiles/test_spirv_unit_tests.dir/assembly_context_test.cpp.o
In file included from /var/tmp/portage/media-libs/vulkan-loader-9999/work/vulkan-loader-9999-abi_x86_64.amd64/external/spirv-tools/external/googletest/googlemock/include/gmock/gmock-spec-builders.h:75:0,
                 from /var/tmp/portage/media-libs/vulkan-loader-9999/work/vulkan-loader-9999-abi_x86_64.amd64/external/spirv-tools/external/googletest/googlemock/include/gmock/gmock-generated-function-mockers.h:43,
                 from /var/tmp/portage/media-libs/vulkan-loader-9999/work/vulkan-loader-9999-abi_x86_64.amd64/external/spirv-tools/external/googletest/googlemock/include/gmock/gmock.h:61,
                 from /var/tmp/portage/media-libs/vulkan-loader-9999/work/vulkan-loader-9999-abi_x86_64.amd64/external/spirv-tools/test/bit_stream.cpp:19:
/var/tmp/portage/media-libs/vulkan-loader-9999/work/vulkan-loader-9999-abi_x86_64.amd64/external/spirv-tools/external/googletest/googlemock/include/gmock/gmock-matchers.h:1623:29: error: conversion to ‘int’ from ‘long unsigned int’ may alter its value [-Werror=conversion]
   typedef MatcherList<sizeof...(Args), Args...> MatcherListType;
                             ^~~

**Comment by pierremoreau** [comment]
This remains an issue when building SPIRV-Tools with GCC 7.1 or higher.

Looking at the code, `typedef MatcherList<sizeof...(Args), Args...> MatcherListType;` (see [gmock-matchers.h, line 1623](https://github.com/google/googletest/blob/master/googlemock/include/gmock/gmock-matchers.h#L1623)) will pass a `std::size_t` as first template argument to `MatcherList` whereas it expects an `int` (see [gmock-matchers.h, line 1558](https://github.com/google/googletest/blob/master/googlemock/include/gmock/gmock-matchers.h#L1558)).

Changing the definition of `MatcherList` to take a `std::size_t` instead of an `int` as first template arguments solves the conversion error and allows to build the whole project without further issues.

**Comment by gennadiycivil** [comment]
Thank you very much for this report. The best way to approach this would be to create a proper PR and submit it for consideration.

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you
