### ISSUE TITLE
MSVC2017 - 32-bit only: atomics cannot be used in validation macros due to alignment problems

### ISSUE THREAD

**Issue by yeswalrus** [google/googletest#1114]
Direct use of atomics causes `error C2718: 'const T1': actual parameter with requested alignment of 8 won't be aligned`

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you

**Comment by npcostes** [comment]
We're having the same issue with VS2015 x86 build only.

Sample program to duplicate error. Must build with Update 3 of VS2015, x86 build (debug or release).

```C++
#include <atomic>
#include <type_traits>
#include "gtest/internal/gtest-internal.h"

class MyIntAtomic
{
public:
	MyIntAtomic(const int64_t value = 0) :
		m_value(value)
	{
	}

private:
	std::atomic<int64_t> m_value;
};

int main(int argc, char* argv[]) 
{
	bool val1 = std::is_convertible<const MyIntAtomic&, testing::internal::BiggestInt>::value;
	bool val2 = testing::internal::ImplicitlyConvertible<const MyIntAtomic&, testing::internal::BiggestInt>::value;
}
```

Here are some thoughts from a discussion with a colleague:

This issue impacts any std::atomic<X> where X is a variable with a sizeof() == 8 on all version of MSVC15 targeting win32. Prior to update 3, faulty code may be emitted by the compiller. Update 3 puts extra restrictions on how we use atomic<int64_t> to make it safe, but disallows some usages such as passing a 64b atomic by value. Behavior on older or newer versions of MSVC before or after MSVC15 are unknown. 

The heart of this is that to fix compiler errors in MSVC15 RTM and updates up through update 2, MSVC15 Update 3 insists that atomics must be aligned. So a long long atomic must be alignas(8). That makes sense, if you're talking about a 64b processor where the std::atomic implementation relies on 8- aligned machine code instructions. 

But on 32-bit, this would need to happen as a spinlock protected thing anyway because there are no hardware atomic 8- byte operations. It's always going to take two fetches or two saves. So on 32b, I personally can't see any reason why you'd need it to be aligned, but there's evidence that MSVC team put thought into it, and that they came to the opposite conclusion. see the comment in <xxatomic> line 161. Perhaps some aspect of their low level implementation requires alignment? 

````C++
// x86's stack is 4-aligned, but atomic<int64_t> needs to be 8-aligned. // Don't change this setting unless you know exactly what you're doing. #ifndef _HAS_CORRECTLY_ALIGNED_ATOMIC_SPECIALIZATIONS 
#define _HAS_CORRECTLY_ALIGNED_ATOMIC_SPECIALIZATIONS 1 #endif /* _HAS_CORRECTLY_ALIGNED_ATOMIC_SPECIALIZATIONS */ 
````

Also see: https://docs.microsoft.com/en-us/cpp/build/conflicts-with-the-x86-compiler?view=vs-2015 -- which talks about "Unaligned locations cannot be used in interlocked operations." -- Interlocked are another way of getting atomic behaviors with a different API. 

HOWEVER: Any variables which are alignas(8), as well as any structs, classes, or unions which must contain alignas(8) members, all cannot be passed on the stack in a 32b architecture because the stack itself is alignas 4. So the alignas(8) ends up putting an artificial limitation on how you can use such variables or classes in your code as well as in thirdparty code. It says you can't pass them by value. It may also prevent their use as non-reference return values, I'm not sure. 

In this particular case, the fault we're seeing is within gtest. Attached is a minimal proof for it, which fails ONLY on MSVC2015 U3 when targeting win32. 
  std::is_convertible (available in C++11 or later only) builds. 
  gtest's testing::internal::ImplicitlyConvertible does not build. 
  The two should be equivalent. 

But even if this particular fault in gtest is fixed, you still have the limitation against passing by value and also maybe returning by value, which will end up having impacts over the place in the code.
