### ISSUE TITLE
Stripping of googletest arguments from argv can lead to crashes on macOS.

### ISSUE THREAD

**Issue by Burgch** [google/googletest#1346]
In [src/gtest.cc#L5326-L5341](https://github.com/google/googletest/blob/a868e618c0607259c63f37d948b72586a13922ff/googletest/src/gtest.cc#L5326-L5341), if an argument is a googletest argument, it is parsed and each successive element of `argv` is shifted left, and `argc` is decremented.

The signature of `main` takes `argc` by copy, but `argv` by pointer. However, on macOS, the functions `_NSGetArgc` and `_NSGetArgv` from `<crt_externs.h>` both return pointers (to `int` and `char**` respectively). The pointer returned by `_NSGetArgv` points to the same block of memory as the `argv` argument passed to main, but the integer pointed to by `_NSGetArgc` is of course not modified by modifying the `int` passed by value as `argc` to `main`.

If library code then tries to inspect the command line arguments via the pointers returned by `_NSGetArgc` and `_NSGetArgv` (such as [this code in Chromium](https://searchcode.com/codesearch/view/86186786/#l-54)), it will see the modified `argv` but `argc` is unchanged. Therefore, it can try to dereference `NULL`, based on the (not unreasonable) assumption that `argc` is a correct count of the elements in `argv`. This can lead to crashes of the entire test executable.

I'm happy to submit a pull request which corrects this behaviour by setting the `int` pointed to by `_NSGetArgc` to the same value as `argc` at the end of the loop in `ParseGoogleTestFlagsOnlyImpl`, only on macOS, and perhaps only if `argv` is equal to `*_NSGetArgv()`, to prevent oddities if a user has constructed their own `argc` and `argv`.

**Comment by dennisferron** [comment]
I can confirm a similar issue is present on Windows when attempting to use Google Test with code which has MFC dependencies.  Code within MFC (and probably elsewhere in Microsoft libraries) relies on the __argc and __targv global macros instead of having argc/argv passed to them.  When Google Test writes nulls to main's argv string pointers, that does also null out the string pointers returned by __targv.  However since argc is an int value (global __argc does involve a pointer, but the argc passed to main is by-value), the actions of Google Test lead to an inconsistent state of global __argc still returning "3" but the latter two are null in __targv.
