### ISSUE TITLE
Bulding gtest_main with gcc-arm-embedded toolchain fails: "template with C linkage"

### ISSUE THREAD

**Issue by mbiberhofer** [google/googletest#1372]
Greetings,

I'm trying to use gtest for my STM32 project. It uses [stm32-cmake](https://github.com/ObKo/stm32-cmake) and the [gcc-arm-embedded](https://developer.arm.com/open-source/gnu-toolchain/gnu-rm) toolchain. The build is executed on Windows 10, using QtCreator.

I set the gtest_disable_pthreads to ON, as the target does not support pthreads. Also, I added "-DGTEST_HAS_POSIX_RE=0 -DGTEST_HAS_CLONE=0 -DGTEST_HAS_EXCEPTIONS=0 -DGTEST_HAS_TR1_TUPLE=0 -DGTEST_HAS_STREAM_REDIRECTION=0 -DGTEST_HAS_RTTI=0" in my CFLAGS. Both debug and release targets are affected.

As I'm using the stm32-cmake files, I defined TOOLCHAIN_PREFIX as the path to the unzipped gcc-arm-embedded release, and set the gcc_stm32.cmake file as my CMAKE_TOOLCHAIN_FILE.

Building the libgmock.a and libgmock_main.a targets works fine, libgtest.a was built correctly, too. But building libgtest_main.a fails with some thousand "error: template with C linkage" and "template specialization with C linkage" error. See the attached cmake & build logs:
[CMakeLog.log](https://github.com/google/googletest/files/1588351/CMakeLog.log)
[BuildLog.log](https://github.com/google/googletest/files/1588353/BuildLog.log)

Any ideas how to resolve this issue? I was a bit intrigued by the fact that both of the libraries are build with exactly the same flags/cmake code("cxx_library(gtest_main "${cxx_strict}" src/gtest_main.cc)", yet only gtest_main has the issue.
Feel free to ask if I you need further information/assistance. :-)

Cheers,
Mario

**Comment by mbiberhofer** [comment]
This issue also prevailed when linking libgtest against my tests.

I replaced -isystem with -I, and everything works fine. so, in googletest/CMakeLists.txt and googlemock/CMakelists.txt, I replaced the lines:
`if (DEFINED CMAKE_VERSION AND NOT "${CMAKE_VERSION}" VERSION_LESS "2.8.11")
  target_include_directories(gtest      SYSTEM INTERFACE "${gtest_SOURCE_DIR}/include")
  target_include_directories(gtest_main SYSTEM INTERFACE "${gtest_SOURCE_DIR}/include")
endif()
`
with:
`if (DEFINED CMAKE_VERSION AND NOT "${CMAKE_VERSION}" VERSION_LESS "2.8.11")
  target_include_directories(gtest      INTERFACE "${gtest_SOURCE_DIR}/include")
  target_include_directories(gtest_main INTERFACE "${gtest_SOURCE_DIR}/include")
endif()
`

And everything works.

**Comment by JohannesWoeber** [comment]
Hi, I tried too compiling gtest with arm-none-eabi-g++ 7.2.1.

I added 
`set(CMAKE_CXX_FLAGS "-DGTEST_HAS_POSIX_RE=0 -DGTEST_HAS_CLONE=0 -DGTEST_HAS_EXCEPTIONS=0 -DGTEST_HAS_TR1_TUPLE=0 -DGTEST_HAS_STREAM_REDIRECTION=0 -DGTEST_HAS_RTTI=0")`
like mbiberhofer suggested

and changed the include directories command as described above. It resulted in the following linker errors:

```
undefined reference to `__sync_synchronize'
undefined reference to `getcwd'
undefined reference to `mkdir'
```

Did it work in the end for you? I saw you used newlib in your Repo. Does that solve that issue?

Thanks

**Comment by JohannesWoeber** [comment]
I "fixed" the getcwd and mkdir errors by throwing those commands out in the hope I wont need them if I dont create report files. I cant find where __sync_synchronize is called for the life of me though.

**Comment by Bu11etmagnet** [comment]
grep the .o files for __sync_synchronize, or rebuild everything with -save-temps and grep the .s files

**Comment by olivierperrier** [comment]
Hello, I tried too to make a gtest compilation but I get some other issues:
To disable unsupported features, I did as JohannesWoeber : set(CMAKE_CXX_FLAGS "-DGTEST_HAS_POSIX_RE=0 -DGTEST_HAS_CLONE=0 -DGTEST_HAS_EXCEPTIONS=0 -DGTEST_HAS_TR1_TUPLE=0 -DGTEST_HAS_STREAM_REDIRECTION=0 -DGTEST_HAS_RTTI=0") set in the CMakeLists.txt, just after:
     set(CMAKE_CXX_EXTERNSIONS OFF)
endif
 I turned off the googletest installation because it is a non sense for bare-metal cross compilation

I get following errors:

gtest-port.h: In function 'void testing::internal::SleepMilliseconds(int)':
/home/oliv/dev/gtest/repository/googletest/googletest/include/gtest/internal/gtest-port.h:1344:27: error: 'nanosleep' was not declared in this scope
   nanosleep(&time, nullptr);

while compiling:
[ 12%] Building CXX object googlemock/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.obj

Did I do a mistake about setting flags, or maybe I should add some dependencies ?
Thanks for your support !

**Comment by gennadiycivil** [comment]
Thank you very much for this report. Unfortunately there appears to be no actionable information.
