### ISSUE TITLE
Option --sort sorts tests and test cases

### ISSUE THREAD

**Issue by jmlundberg** [google/googletest#1425]
Although it's a bad idea to rely on the order of execution when writing unit tests, it's sometimes useful to be able to keep the order fixed across link order, compiler (version) changes, etc. 
Two particular cases: reproducing test results from build/test servers and meta-regression testing of test output.

I've implemented such a `sort` option, that works very similarly to the `shuffle` option: sorting death tests, ordinary tests, and test cases, by `.name()`, and `std::string operator <`.

It works naturally in combination with shuffle: `sort` and `shuffle` gives a shuffled but constant (deterministic) execution order. It also allows easier comparison of log files and meta-regression tests based on test output.

I'd be happy to prepare a pull request.

**Comment by gennadiycivil** [comment]
Sorry for the long delay. We had a lively discussion, it is just so fundamentally wrong to rely on any order in until tests execution whatsoever that we specifically want to disallow it and not make it easy in any shape or form
If you do need the order, you can compile one test per binary - run it - compile next test per binary - run it , etc.... which is kludgy but kludgy by design :)

**Comment by SteveS-Serrano** [comment]
It is difficult to understand such a mindset. Tests run in a certain order fail. I want to debug this. You make it impossible.

**Comment by ehsberl** [comment]
We extensively use Google Test, and a change similar to this, where the test order could be decided from the command line, would greatly benefit us.

Currently, our code under test heavily relies on static data and singleton patterns. Testing such code have often revealed issues that closely resemble the problems that occur with interdependent tests. For instance, Tests A and B pass individually and when A is followed by B. However, when B is followed by A, Valgrind-issues arise.

We have deduced that, while these errors are exposed through different test orders, the actual problem lies in the code under test and how it utilizes static data and singletons. In fact, the memory-issues arise because of interdependencies between static data and singletons. What is happening is that due to incomplete clean-up of static data and singleton patterns, data persists and survives from one test and affects another, causing memory to be dynamically allocated, which is not destroyed at test completion.

One of our test suites comprises 20 distinct tests. If we were to execute every possible permutation of these tests, we would need to run 20 factorial, which is equal to 2432902008176640000 times. If each test took 1 second to run, we would have to wait for 77 billion years for all of them to complete. This realization has prompted us to recognize the necessity of testing smarter than simply randomly selecting a few test orders from a pool of 2432902008176640000 test orders.

What we finally decided to do was to systematically test only a very small subset of these tests. We chosed to test every possible pair of tests, in both orders. By using Google Test in this manner and in conjunction with Valgrind, we could effectively reveal all problems related to memory management that had to do with interdependencies between static data and singletons. In fact, after implementing this and fixed all the problems that this approach revealed to us, our tests are now free from intermittent errors.

Unfortunately, we had to resort to modifying Google Test and implement our own test order function, since Google Test does not support the option of specifying a specific test order.
