### ISSUE TITLE
MSVC builds: static libs' PDB files are not installed

### ISSUE THREAD

**Issue by a-tinsmith** [google/googletest#1440]
gtest: latest master
CMake: 3.10
MSVC: 2017 x64

When building with MSVC then PDB files are generated in respective build directories (Debug, Release, ...) but not installed.

The absence of PDB's causes the following linker warning on the client side:
`gtestd.lib(gtest-all.obj) : warning LNK4099: PDB 'gtest.pdb' was not found with 'gtestd.lib(gtest-all.obj)' ...`

Additional problem: PDB files have plain `<target>` names, `CMAKE_DEBUG_POSTFIX` variable is ignored when PDB filenames are formed. That makes them identical for Debug vs Release builds and impossible to install in the same directory.

PDB filenames can be set in the `cxx_library_with_type` function (in the `googletest\cmake\internal_utils.cmake` file):
```cmake
if (MSVC <and not shared build>)
  set_target_properties(${name}
      PROPERTIES
      COMPILE_PDB_NAME_DEBUG ${name}${CMAKE_DEBUG_POSTFIX}
      COMPILE_PDB_NAME_RELEASE ${name}
      COMPILE_PDB_NAME_MINSIZEREL ${name}
      COMPILE_PDB_NAME_RELWITHDEBINFO ${name})
endif()
```
Then in the install section (`INSTALL_GMOCK` and `INSTALL_GTEST`) we have to handle these files explicitly:
```cmake
install(DIRECTORY
  $<TARGET_FILE_DIR:gmock>/
  $<TARGET_FILE_DIR:gmock_main>/
  DESTINATION "${CMAKE_INSTALL_LIBDIR}"
  FILES_MATCHING PATTERN "*.pdb")
```

**Comment by matlo607** [comment]
@a-tinsmith, please could you test again with the branch master ?
#1795 was merged.

**Comment by a-tinsmith** [comment]
Hi,
I just tested it with the master and VC2017 (v15.8.6) - everything works properly. PDB's are named correctly and installed with other binaries as expected.

**Comment by Anon243243243** [comment]
For anyone who's still coming across this warning, and hitting this thread on google, it took me a minute to figure out what was happening:

My guess is that the problem was fixed in the cmake files, but the MSVC 2010 solution that's committed to the repository is still incorrect. Thus, if you're like me and just opened the MSVC solution, upgraded it to whatever MSVC you're using, and built, the warning will still happen.

This is made furtherly confusing by the fact that, as long as you leave the output files from the MSVC 2010 build on your disk, the PDB files THERE will get referenced by other unrelated projects that link the .lib files you made, even if the .lib files are moved to a completely different location. It seems that the original build path, embedded in the .lib file, is included as a path when searching for PDB files (I never knew this before now...) So, if you, say, unpack googletest-master.zip in C:\temp\googletest, build, copy the lib files to D:\work\myproject, and clean build myproject, there will be no warning... but as soon as you erase C:\temp, the warning will reappear. Took me 3 or 4 times of rebuilding and thinking I'd fixed the problem to realize what was happening!

In order to fix it for real, if you don't want to use cmake, you can just copy the .pdbs into the same folder as your .lib files, but as mentioned above, the names of the .pdb files are screwed up, so you'll have to create separate folders for Debug, Release, etc.

Hopefully this message is of use to someone!
