### ISSUE TITLE
Question about ColoredPrintf on Windows

### ISSUE THREAD

**Issue by Dekken** [google/googletest#1487]
Hi there

I have been experiencing a linker error with MSVC 2017 on windows when attempting to use 

```ColoredPrintf``` using extern

Is there something special I have to do that you know of?

Reference: https://github.com/Dekken/tick/blob/eq/lib/cpp-test/serialization/solver_gtest.cpp#L66

**Comment by anb0s** [comment]
We have similar issue, but it looks like the method signature was changed from googletest 1.8.0 

`void ColoredPrintf(GTestColor color, const char* fmt, ...)`

to master:
`static void ColoredPrintf(GTestColor color, const char* fmt, ...)`

The method is in namespace internal and there is no interface to it. Using it as external is not possible anymore, because it's now static in compile unit gtest.cc

It means "should not be used from out side"...

**Comment by Dekken** [comment]
[This was my hack](https://github.com/Dekken/tick/blob/master/lib/cpp-test/serialization/include.h#L51)

**Comment by gennadiycivil** [comment]
Thank you very much for this report. The best way to approach this would be to create a proper PR and submit it for consideration. Basically you are asking to make ColoredPrintf available as a public function. I don't see why not but it would only be possible to check for sure when there is a proper PR to consuder

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you
