### ISSUE TITLE
Valgrind issue in `gtest-printers.cc`

### ISSUE THREAD

**Issue by m-chaturvedi** [google/googletest#1610]
To reproduce:

```
#include "gtest/gtest.h"
#include <iostream>
#include <cmath>
#include <functional>
using std::function;

class FooTest : public ::testing::TestWithParam<function<double(double)>> {
        protected:
                virtual void SetUp() {
                }
                virtual void TearDown() {
                }
                double a_;
};


TEST_P(FooTest, Check) {
        a_ = GetParam()(547.0);
}

INSTANTIATE_TEST_CASE_P(
                TestWithParametersC1, FooTest, testing::Values(
                        [](double x) { return std::abs(x); },
                        [](double x) { return std::log(x); }
                        ));

int main(int argc, char **argv) {
        ::testing::InitGoogleTest(&argc, argv);
        return RUN_ALL_TESTS();
}

```
[Output gist](https://gist.github.com/m-chaturvedi/e5f178f553ad7302fe0b36a0b467d6f0)

**Comment by sbenzaquen** [comment]
On Fri, May 25, 2018 at 2:24 PM Mmanu Chaturvedi <notifications@github.com>
wrote:

> To reproduce:
>
> #include "gtest/gtest.h"
> #include <iostream>
> #include <cmath>
> #include <functional>
> using std::function;
>
> class FooTest : public ::testing::TestWithParam<function<double(double)>> {
>         protected:
>                 virtual void SetUp() {
>                 }
>                 virtual void TearDown() {
>                 }
>                 double a_;
> };
>
>
> TEST_P(FooTest, Check) {
>         a_ = GetParam()(547.0);
> }
>
> INSTANTIATE_TEST_CASE_P(
>                 TestWithParametersC1, FooTest, testing::Values(
>                         [](double x) { return std::abs(x); },
>                         [](double x) { return std::log(x); }
>                         ));
>
> int main(int argc, char **argv) {
>         ::testing::InitGoogleTest(&argc, argv);
>         return RUN_ALL_TESTS();
> }
>
>
> Output gist
> <https://gist.github.com/m-chaturvedi/e5f178f553ad7302fe0b36a0b467d6f0>
>

This is somewhat expected when trying to print objects that have no printer.
The fallback printer will just dump the bytes of the object, which could
read uninitialized data.
In your case, I suggest not using std::function as your test parameter and
instead use your own type. That way you can provide an operator<< for it.
The printed string is used in the output so it is useful to have one that
helps you identify the test instead of just byte dumps.

Another option is to use an enum as the parameter and convert to the
std::function separately.

Eg:

enum Op {
  Abs,
  Log
};

class FooTest : public ::testing::TestWithParam<Op> {
        protected:
                double a_;
};

std::function<double(double)> OpToF(Op op) {
  switch(op) {
    case Abs: return [](double x) { return std::abs(x); };
    case Log: return [](double x) { return std::log(x); };
  }
}

TEST_P(FooTest, Check) {
        a_ = OpToF(GetParam())(547.0);
}

INSTANTIATE_TEST_CASE_P(
                TestWithParametersC1, FooTest, testing::Values(Abs, Log));

**Comment by m-chaturvedi** [comment]
Thank you for the suggestion and the quick reply!

**Comment by pitrou** [comment]
While the workaround (add a `operator<<`) is ok, it quickly gets cumbersome when you have to do so in multiple places to avoid Valgrind errors.

The frustrating thing here is that the parameter's string representation is only used when a test failure occurs, but it's always computed when registering the parameterized tests. It would be better if `testing::internal::ParameterizedTestCaseInfo<T>::RegisterTests` didn't try to compute a string representation.
