### ISSUE TITLE
Linking a Debug test project with a Release dll crashes the test executable.  

### ISSUE THREAD

**Issue by benvanbasten** [google/googletest#1765]
We generally want to keep our build server repo with external libraries clean and without debug versions . Unfortunately, linking a gtest release DLL in a debug project causes a crash. 

Is there a workaround (except using the debug dll ;) ) such that we only require the release build?

VS2015, Win10

**Comment by staffantj** [comment]
Speaking individually, as I have no link to the project, other than as a fellow user.

The issue is quite likely (but not necessarily limited to) the problem of objects having a different layout in debug and release mode compiled code under MSVC. This is for instance why you get ITERATOR_DEBUG_LEVEL mismatch errors if you try to statically link a debug library into a release application. This especially is an issue when dealing with dynamically loaded libraries.

In the spirit of "build the library using the exact same switches as the code pulling it in", I'm afraid the best suggestion I can offer is that you keep a debug copy of the library on hand. Even better is to have a test target in your project and directly build it into the target code - then you know you don't have any hidden ABI issues going on.
