### ISSUE TITLE
In debug build: gtest.pc.in provides -lgtest flag but libgtestd.a is built.

### ISSUE THREAD

**Issue by mjfryc** [google/googletest#2174]
When building gtest with CMAKE_BUILD_TYPE Debug, googletest/cmake/gtest.pc.in contains hard-coded` -lgtest` flag, but libgtest**d**.a file is built.

I think that this flag should be templated.

**Comment by r00t-** [comment]
that behaviour (appending the `d` is defined here:
https://github.com/google/googletest/blob/f7902802f1a61140e188223fb6d1c95925cbec4a/googletest/cmake/internal_utils.cmake#L160

**Comment by qjoyel** [comment]
This change caused a regression if Google Test is compiled with CMake without specifying the Debug postfix with MSVC: the CMake installed scripts are broken (cannot consume a pre-compiled GTest package) and .pdb file is misnamed (contains ...-NOTFOUND). I think this fix is inappropriate and that the .pc.in file should be modified instead of removing the postfix, which is useful when compiling, installing, or packaging Google Test with a CMake multiconfig generator. Would it be possible to revert and review this fix? The workaround (which breaks the vcpkg part) is to run the configuration with -DCMAKE_DEBUG_POSTFIX=d.

See #3843

**Comment by r00t-** [comment]
the removed line that hardcodes the suffix is definitively broken, specifically when not updating the package-config file accordingly.

as already pointed out at https://github.com/google/googletest/pull/3453#issuecomment-880925725 , the possible improvement is to template the pkg-config file to reference the name of the library as it was generated.

also note that FindGTest.cmake is third party code, which has come to rely on this broken behaviour (see https://github.com/google/googletest/pull/3453#issuecomment-880744545 ), have not checked if there is a bug report on their end.

i understand that this is frustrating,
it is equally frustrating for the other side - anybody installing _only_ the debug build, and then wondering why the binary that was generated is not found by the linker via pkg-config because it suddenly has an extra `d` in the name - and that is quite clearly a bug.
