### ISSUE TITLE
Why is googletest not distributed as shared library?

### ISSUE THREAD

**Issue by Apromixately** [google/googletest#2184]
It seems there is a reason that googletest should not be used as a shared library.

This has caused some confusion: 
* https://askubuntu.com/questions/145887/why-no-library-files-installed-for-google-test
* https://stackoverflow.com/questions/13513905/how-to-setup-googletest-as-a-shared-library-on-linux

Mostly due to the fact that both debian and ubuntu don't include the actual library in the packages now (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=802587).

There seem to have been explanations for this in the past at
https://code.google.com/p/googletest/wiki/FAQ#Why_is_it_not_recommended_to_install_a_pre-compiled_copy_of_Goog
but that link is now dead.

I think it would be good to give an explanation of this somewhat surprising behavior in the documentation somewhere or, if the reason does not exist anymore, suggest to package maintainers that a more standard distribution method can now be used.

**Comment by ngie-eign** [comment]
I agree. Why isn’t shared libraries the default, with static libraries being the backup, or why aren’t both compiled by default?

**Comment by ndevenish** [comment]
This advice was removed in 5437926b2213b1c45c2f34bd858734de90e5fffd with the message "docs sync" - The last version can be found [here](https://github.com/google/googletest/blob/36066cfecf79267bdf46ff82ca6c3b052f8f633c/googletest/docs/faq.md#why-is-it-not-recommended-to-install-a-pre-compiled-copy-of-google-test-for-example-into-usrlocal).

It'd be nice to know if this advice has been officially dropped or if it was just an accident - I'm not sure what "docs sync" means or what it's being synced to.

**Comment by asoffer** [comment]
At Google, we rely primarily on static linking, so part of the reason is historical. We are somewhat resistant to shared libraries as they can often lead to further maintenance burden. Moreover, it is important that you compile Googletest with the same compiler and compiler flags as the test you are writing to avoid ODR violations. We are not categorically opposed to providing a shared library, but doing so with a Live At Head approach is nontrivial due to these constraints.

The advice has not been officially dropped. As best I can tell it is just no longer a frequently asked question. I'll look into adding it back.
