### ISSUE TITLE
Memory Leaks on Windows using VLD

### ISSUE THREAD

**Issue by Jiwan** [google/googletest#2255]
It seems that some leak issues on Windows have been partially fixed in the past:
See: #624 , #692, #757 and #970

This solution only works for MSVC's leak detector, but does not help for other leak detectors.
For instance, [VLD](https://github.com/KindDragon/vld/wiki/Using-Visual-Leak-Detector) still reports a leak when the tests are done running. One could call these leaks "false-positives" as the memory is properly cleaned when the process is done, but having them trigger on various tools make it really inconvenient in any case.

If a proper fix for these issues (i.e: do deallocate before exiting) could be applied, that would greatly improve the situation.

Thanks!

**Comment by gennadiycivil** [comment]
Thank you very much for this report. The best way to approach this would be to create a proper PR and submit it for consideration.

**Comment by bert8128** [comment]
On my project we also use VLD as the leak analysis tool as it is better than the MS standard for scripted jobs, and these false positives mean that we can't use various macros (eg ASSERT_NO_FATAL_FAILURE), or have to patch them locally.  It would be a great improvement to gtest if the static pointers could be coded using std::unique_ptr as the dynamically allocated memory will then be returned in static data destruction and VLD then does not report a leak.
Hopefully this can make it into 1.9.

**Comment by EricWF** [comment]
Any address that's reachable when program termination begins is not a leak. Your tool is wrong.

I've spent the past two weeks chasing down race conditions during destruction, and it's been invaluable to me that Google Test doesn't create more races or use-after-free's while tearing down the tests. The current behavior does not exert influence over buggy code, which is what you want.

**Comment by bert8128** [comment]
"Any address that's reachable when program termination begins is not a leak. Your tool is wrong."
I totally disgree.
1) This assumes that memory is the only resource freed - what about other resources - file handles,socket connections etc? It is reasonable for a program to want to close these in a defined way, even if the holder is static.  In these cases, the programmer would want to be warned if they are not doing so.
2) VLD is not "my tool" - it is one of the main tools for trapping leaks in Windows.  Valgrind is not available on Windows, so by saying "valgrind has the right model" are you implying that we should only be leak checking on Unix?

All this being said, I do understand the problem of static data destruction order, and just because my project has solved the problem shouldn't mean that every project should have to solve it in order to use gtest.
As a compromise, would it be reasonable to suggest that necessarily static objects could be optionally deleted on program termination, determined by some define or similar?
