### ISSUE TITLE
Question about docs of gtest & gmock

### ISSUE THREAD

**Issue by ant35rookie** [google/googletest#2337]
Hello, thank you for this great project

I have two questions!

1. Do you think that gtest / gmock need translated docs in other languages in main branch?
(like googlemock/docs/some_language/cook_book.md)

2. Do I need to make an issue and get agreement before I submit PR? (if it fixes typo in [docs](https://github.com/google/googletest/tree/master/googlemock/docs) only)

Thank you ~!

**Comment by EricWF** [comment]
Reopening. This is a great question.
I would like to see this issue discussed further.

**Comment by gennadiycivil** [comment]
It would be great to have documentation in other languages, yes.
We would have to develop an on-going process so once the docs are there they stay in sync with the changes though.

**Comment by ant35rookie** [comment]
Thank you for the comment!
I'm actually translating docs into Korean and I think that it would be helpful for other Koreans too

I will try to check it regularly and sync up the changes

And I believe that engineers in my country would help to update it if initial version is there ^^;

**Comment by gennadiycivil** [comment]
This is really awesome, thank you so much.

**Comment by hyukmyeong** [comment]
Hello!

This issue is for making googletest, gMock docs in Korean version^^

I think that my work is almost done !
And while I'm doing this I found below as awell

It must be grateful if you review these things !

1. I found typos and so make https://github.com/google/googletest/pull/2384
2. I think markdown link syntax `{#where}` is not working in github
3. I found term "parent class", "base class" are mingled, Do you think they need to be unified?
4. In advanced.md, it describes "pimpl" as "private Implementation", It is correct cuz the context is saying about testing private code but still "pointer to Implementation" looks more general term

Please kindly review https://github.com/google/googletest/pull/2384 !
and if it needs to be revised I think I could make PR on 2~4 as well
