### ISSUE TITLE
Attaching files to test results

### ISSUE THREAD

**Issue by nhekman** [google/googletest#2425]
I believe this is a feature request--or if the feature already exists or has already been requested and I've just missed it, please point me to it!

NUnit and Microsoft's managed test framework have methods like `TestContext.AddResultFile`, which cause the test status window in Visual Studio to include links to all attached files. This is very helpful to us, as some of our tests produce CSV files, xml files, and other files that are needed to troubleshoot problems when the tests fail.

[This feature was added to NUnit a couple years ago.](https://github.com/nunit/nunit/issues/1670)

Here's what the output looks like:
![attachments in visual studio unit test result window](https://user-images.githubusercontent.com/30095412/63623135-016ab180-c5b6-11e9-862d-f69c2ec7f4a4.jpg)

**Comment by asoffer** [comment]
Thank you for this request, and apologies for the delay. Unfortunately, I do not believe we are going to be implementing this. This is more primarily a logging facility rather than a testing facility, and while admittedly the two overlap slightly, we believe streaming to stderr and stdout is sufficient for most use cases.
