### ISSUE TITLE
CppCheck error in gtest-port.h

### ISSUE THREAD

**Issue by narad-git** [google/googletest#2451]
The following error was found by CppCheck:
[/usr/local/include/gtest/internal/gtest-port.h:2126]: (error) Shifting signed 64-bit value by 63 bits is undefined behaviour

The code in question is:
```
const BiggestInt kMaxBiggestInt =
    ~(static_cast<BiggestInt>(1) << (8*sizeof(BiggestInt) - 1));
```

My command line:
cppcheck -I /usr/local/include -D__GNUC__ *.cpp

**Comment by kuzkry** [comment]
Cool, I've also recognised this problem since I've been recently heavily focused on this file. I think you're right. The standard says:
> The result of E1 << E2 is E1 left-shifted E2 bit positions; vacated bits are filled with zeros. [...] If E1 has a signed type and nonnegative value, and E1 × 2^E2 is representable in the result type, then that is the resulting value; otherwise, the behavior is undefined.

In this case:
E1 is 1
E2 is 8 * 8 - 1 => 63
And 1 * 2^63, which is just 2^63 is isn't representable in int64, which is exactly 2^63 - 1, this is unsafe.

What's even funnier, in C++14 this would no longer be undefined behaviour but that's a different story.
Anyway, are you willing to work on this issue? If not, I can handle it.

**Comment by narad-git** [comment]
Sure, I'll give it a shot.

**Comment by kuzkry** [comment]
Hey, no need now, it's done :) Check the referenced issue.

**Comment by narad-git** [comment]
Even better. Thank you!
