### ISSUE TITLE
Why gmock implement not use the “Modify Function Pointer Address”？

### ISSUE THREAD

**Issue by answer3y** [google/googletest#2500]
We know mock has many way。 Gmock use virtual function to mock，some other company use “Modify Function Pointer Address” to mock。

Why google choose this way？ （virtual function）

**Comment by asoffer** [comment]
The short answer is that this is largely just historical.
A slightly longer answer is that I don not know of a way to simply modify the function pointer without invoking undefined behavior. If there is a way, it's unlikely we will use this approach because the effort to switch would be enormous compared to the benefit.
