### ISSUE TITLE
Missing Declarations

### ISSUE THREAD

**Issue by NaruFGT** [google/googletest#2661]
When building with the GNU C++ compiler with the warning option `-Wmissing-declarations` several warnings are generated due to the prolific practice of definitions themselves providing their prototypes.
As projects may use `-Werror` and `-Wmissing-declarations` options, this may cause projects which include googletest to fail to build.
One may take additional steps to customize warnings sent to components of the build, but I think the correct solution is to provide explicit declarations in googletest sources.

```
Building CXX object ThirdParty/googletest/googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
In file included from ../ThirdParty/googletest/googletest/src/gtest-all.cc:42:
../ThirdParty/googletest/googletest/src/gtest.cc:631:17: warning: no previous declaration for ‘testing::AssertionResult testing::internal::HasOneFailure(const char*, const char*, const char*, const testing::TestPartResultArray&, testing::TestPartResult::Type, const string&)’ [-Wmissing-declarations]
  631 | AssertionResult HasOneFailure(const char* /* results_expr */,
      |                 ^~~~~~~~~~~~~

  ...
```

For reference, the project I encountered this issue in is [xcbuild](https://github.com/facebook/xcbuild).

**Comment by asoffer** [comment]
Is this warning simply that `HasOneFailure` does not have a separate declaration seen before-hand? In other words, would declaring it *immediately* before the definition silence this warning?

**Comment by NaruFGT** [comment]
Yes, that would indeed silence the warning. It is not only HasOneFailure() but also:

googletest/src/gtest.cc
- ValidateTestPropertyName()
- GetAnsiColorCode()
- ColoredPrintf()
- PrintFullTestCommentIfPresent()
- ParseFlagValue()
- ParseBoolFlag()
- ParseStringFlag()
- ParseGoogleTestFlag()
- LoadFlagsFromFile()

googletest/src/gtest-death-test.cc
- DeathTestAbort()
- StackGrowsDown()

googletest/src/gtest-port.cc
- CaptureStream()
- GetCapturedStream()

I'm not sure if these aren't exposed in the headers and thus explicitly declared because they're only used internally, but if they need to remain not exposed, declarations could be placed in src/gtest-internal-inl.h

From _Using the GNU Compiler Collection (GCC)_:
> -Wmissing-declarations
> Warn if a global function is defined without a previous declaration. Do so _even if the definition itself provides a prototype_. Use this option to detect global functions that are not declared in header files. In C, no warnings are issued for functions with previous non-prototype declarations; use -Wmissing-prototypes to detect missing prototypes. In C++, no warnings are issued for function templates, or for inline functions, or for functions in anonymous namespaces.

**Comment by asoffer** [comment]
Thanks for the clarification. There are two parts to this I think are worth addressing separately.
1. Does this provide value today?
2. Is conforming to -Wmissing-declarations worth doing in the future.

For (1), I am unconvinced, but if you wanted to declare these functions as static, that should silence the warning and I'd happily look at a PR to do so.

For (2), I don't believe turning this flag on for GoogleTest (or most other projects) is worthwhile. My take on this is that it may helps you find potential linker errors slightly earlier but has a very low signal-to-noise ratio. It may also help reduce linker input sizes by reminding you to declare static functions static, but the benefit is marginal, since it doesn't apply to the typical big offenders (templates).

With that in mind, I'm going to close this issue with "no, I do not think we will promise to be -Wmissing-declarations clean." However if you wish to send a PR to declare these functions as static (or put in an anonymous namespace), I would welcome such a PR.

**Comment by NaruFGT** [comment]
Thanks for the consideration. I do like the idea of declaring those functions static, I'll give that a try and it may be a worthwhile PR if it works out.

**Comment by ni4** [comment]
Update: as of commit 482ac6e Googletest refuses to build on systems with `-Werror=missing-declarations` due to ColoredPrintf() function with missing declaration.
