### ISSUE TITLE
Add install instructions

### ISSUE THREAD

**Issue by fulldecent** [google/googletest#2664]
Can installation instructions please be added to this project.

Previously the team here had helped to set up builds for Gumbo Parser. But the instructions are no longer working and now he build is broken at

https://github.com/google/gumbo-parser

Thank you

**Comment by sakshi-1604** [comment]
I am on it

**Comment by sakshi-1604** [comment]
Can I do it?

**Comment by alokVerma749** [comment]
can I do this, I really want to collaborate with the company

**Comment by aMetallurgist** [comment]
Can someone clarify what this issue is requesting? The documentation contains at least two installation quickstart guides:

- https://google.github.io/googletest/quickstart-bazel.html
- https://google.github.io/googletest/quickstart-cmake.html

Are we requesting to add installation instructions to setup googletest to run the gumbo-parser library's tests? If so, then gumbo-parser's [README file](https://github.com/google/gumbo-parser/blob/master/README.md) already contains an installation guide that details how to run googletest. The description could be enhanced, but that request should be made on gumbo-parser's repo. 

We might want to consider closing this issue.

**Comment by fulldecent** [comment]
I forget the relationship between googletest and gumbo-parser. That was the motivation for opening the issue here.

Either way I have looked into this, and committed some partial fix at https://github.com/google/gumbo-parser/pull/417

And overall I don't any issue relevant against googletest now. 

Thank you, closing.
