### ISSUE TITLE
Output Report Format

### ISSUE THREAD

**Issue by Jason-Ltiger** [google/googletest#2704]
Hi：
GTEST can output XML reports. How to output HTML web reports is more convenient and intuitive.
Do I need to transform XML reports?How to convert if it could。

**Comment by asoffer** [comment]
The XML web reports are designed to be consumed by tools rather than by humans. We do not provide a direct to HTML output. You can either use the text human-readable output (default) or write a tool to transform the XML to a format you prefer, but GoogleTest does not provide any way to do this explicitly.
