### ISSUE TITLE
Why gmock is designed for virtual method (nearly)?

### ISSUE THREAD

**Issue by luckystone60** [google/googletest#2705]
I have read the resolution to mock non-virtual methods in cook book, but I can't change the production code. So, Why gmock is designed for virtual method (nearly)? I think there are a lot of situations where we can't change the production code and we need to mock non-virtual or static functions,  so what should we do?

thank you very much!

**Comment by hyukmyeong** [comment]
Hello?

In my opinion you can use mock objects with inheritance, templates, and macro replacements

Even though most of documents are describing it with inheritance 
you can still find how to use gMock with template when you cannot change DOC
※ reference [here](https://github.com/google/googletest/blob/master/googlemock/docs/cook_book.md#mocking-non-virtual-methods-mockingnonvirtualmethods)

and optionally you can use macro replacement as well;;

**Comment by asoffer** [comment]
This is partially a legacy decision, but it is also one of the easiest ways to inject/override behavior in C++. Using templates is also possible, but for that approach we don't need much of the gMock machinery.

Overriding definitions with macros is a dangerous proposition that we would like to avoid.

In general, we do feel strongly that the production code needs to be written in a way that makes it testable (whether that's with GoogleTest or any other framework). Production code needs to be modifiable at some level, so that when tests uncover bugs, they can be fixed. If the production code can be modified, hopefully it can also be modified to make it more testable.
