### ISSUE TITLE
std::complex comparison

### ISSUE THREAD

**Issue by lkoenig** [google/googletest#2708]
As a user of GTest I would like to be able to compare complex numbers defines with std::complex the same way I compare floating point number.
I would like to have corresponding 'std::complex' matcher for
  - `FloatEq`
  - `FloatNear`
  - `NanSensitiveComplexFloatEq`
and their double equivalents:
   - `ComplexEq`
   - `ComplexNear`
   - `NanSensitiveComplexDoubleEq`
#1432 is a similar issue.

**Comment by asoffer** [comment]
One subtlety is that distance is slightly more ambiguous for complex numbers. Both the L^2 (euclidean) and L^1 (manhattan) distances make a lot of sense, and depending on your use case, one may be preferred over the other. For floats and double's these distances are the same (essentially because of the one-dimensionality of real numbers).

I'm not sure that GoogleTest should be the one to make these decisions, given that we do not have the expertise to know which is most commonly used it which contexts.

This is to say, we're not outright against having this, but we believe that
1. Before providing a new API and making the long-term promises that come with that, we would like to see some implementation experience.
2. Given that these matchers can be written as custom matchers, we would encourage you to pursue that route.
3. If after doing #2, you feel strongly that the API is stable and broadly useful, we would happily consider moving them into the GoogleTest.

**Comment by lkoenig** [comment]
For equality ComplexFloatEq the definition is unambiguous: Numbers are equals if both their real part and imaginary parts are.
The modulus of a complex number is pretty well defined (https://en.wikipedia.org/wiki/Complex_number#Modulus_and_argument). The distance of 2 numbers beeing define as the modulus of their differences leads to an unambiguous definition of the ComplexFloatNear where 2 numbers are Near each other is the modulus of their difference is less than the radius of proxsimity (same definition as for real umber case).
That are the definition implemented in the attached pull request.

**Comment by asoffer** [comment]
It's true equality is easy (ignoring NaN, Inf, negative zero, and the other annoyances of floating point numbers). What concerns me is the "near" part.

One might reasonably talk about a vector of doubles as being near another if all components are near each other. This is the Manhattan distance and a very different metric from the Euclidean distance. Depending on the context one of these is obviously what you want and the other is obviously not. However, which one is preferred is strongly dependent on context. I do not believe Googletest should be making this decision
