### ISSUE TITLE
Gtest compile error AIX

### ISSUE THREAD

**Issue by Marf97** [google/googletest#2790]
Hi,

I'm having trouble building newest version of gtest on AIX 6.1. I would like to build it with g++ not AIX xlc. After I downloaded release, opening it the procedure how I got to my error is:
```
cd googletest-release-1.10.0
mkdir build
cd build
cmake ..
make
```
I'm getting tons of errors like this:
```
googletest-release-1.10.0/googletest/include/gtest/gtest.h:2299:1: error: template with C linkage
 template <typename T1, typename T2>
 ^~~~~~~~
```
cmake output:
```
cmake ..
-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- Check for working C compiler: /opt/freeware/bin/gcc
-- Check for working C compiler: /opt/freeware/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /opt/freeware/bin/c++
-- Check for working CXX compiler: /opt/freeware/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: /opt/freeware/bin/python (found version "2.7.17")
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - found
-- Found Threads: TRUE
-- Configuring done
-- Generating done
-- Build files have been written to: MY PATH
```

**Comment by Marf97** [comment]
Just to put some more context. That AIX machine is quite outdated and there is some possibility of missing libs or something else. I was trying to satisfy all requirements. If the problem is connected to `CMAKE_HAVE_LIBC_PTHREAD - Failed` please tell me what is needed because I couldn't find it in AIX toolbox or anywhere else.

**Comment by asoffer** [comment]
Unfortunately AIX is an unsupported platform. This could be our bug, or a bug in g++'s compilation for that platform. If you determine what's wrong we'd welcome a PR. But we don't have these machines to test on and aren't familiar with them so we unfortunately cannot be of much help.

**Comment by istvangonczi** [comment]
The problem is : any -isystem directory location on the g++ commandline causes all include files to be silently wrapped in extern "C" { ...}.  You need to change all -isystem -s to -I.    (lowercase -isystem ti uppercase -i)  and you will be able to compile with gcc. ( g++) . This is just a gcc quirk on Aix.

**Comment by istvangonczi** [comment]
One more thing.. so wrapping these include files causes all template code defined in those to fail, because c linkage disables decorations, which are needed for templates. All the compile errors you see are caused by this.   i was able to compile on aix 6.1 using the Ibmfreeware yum-installed gnu 8.3 toolchain.  (this is in turn configured to use the IBM native assembler, and ld)
