### ISSUE TITLE
googlemock/docs/for_dummies.md: broken link: Understanding Uninteresting vs Unexpected Calls.

### ISSUE THREAD

**Issue by ElectricRCAircraftGuy** [google/googletest#2792]
On this page: https://github.com/google/googletest/blob/master/googlemock/docs/for_dummies.md

This link:

> See [Understanding Uninteresting vs Unexpected Calls](https://github.com/google/googletest/blob/master/googlemock/docs/cook_book.md#uninteresting-vs-unexpected).

...is broken.

Please update to this one: https://github.com/google/googletest/blob/master/googlemock/docs/cook_book.md#understanding-uninteresting-vs-unexpected-calls-uninteresting-vs-unexpected

**Comment by asoffer** [comment]
This is annoyingly subtle. The links work as expected internally, after the automated externalization process, they point to the right file but as source rather than the formatted markdown doc. I think that, in the short/medium-term this is something we're going to have to live with unfortunately, though I'll look into fixing the automation that handles this internally as well.
