### ISSUE TITLE
Build fails after Merge pull request #2755

### ISSUE THREAD

**Issue by Guy-Rawsthorn** [google/googletest#2882]
Our implementation of google test repo now fails with error 
```
CMake Error at CMakeLists.txt:129 (set_target_properties):
  set_target_properties called with incorrect number of arguments.
```
This error compliments the change which occurred in https://github.com/google/googletest/commit/cb44c86c1aaf31b26797728e93acc950c01dbd5b
Has the implementation of this framework recently changed?
Best
![image](https://user-images.githubusercontent.com/29066512/83870560-6434d000-a726-11ea-812b-1578daec2773.png)

**Comment by erthink** [comment]
There is one of the correct and simple solutions to this problem.
See https://github.com/erthink/erthink/commit/a4428d17ca8991d3ecd0b8e2ae409db793eaf578

**Comment by Guy-Rawsthorn** [comment]
Thank you - we found a fix for this issue by forcing the google test version to 1.10.0.
RUN git clone --single-branch --branch release-1.10.0 https://github.com/google/googletest.git

**Comment by Seigfreidy** [comment]
![image](https://user-images.githubusercontent.com/36716662/96067378-3463b900-0ecc-11eb-9599-8d0b860772fb.png)
I just met the same problem.

**Comment by witeyou** [comment]
same problem in Ubuntu 18.04.5 LTS.

**Comment by Ansudeen** [comment]
I'm getting the same issue... can we reopen this issue?

**Comment by clemente0420** [comment]
same issue

**Comment by XavierAudier** [comment]
I was running into the same issue, but I found that I had made a mistake:
I had copied the gtest/googletest folder into my project, and running cmake using the googletest folder as working directory.

When copying the whole gtest folder, and using the gtest folder as working directory, cmake ran without issues.
This is because the `GOOGLETEST_VERSION` variable is defined in the `CMakeList.txt` file present in the gtest directory, but not in the `CMakeList.txt` file present in the gtest/googletest one.

**Comment by XavierAudier** [comment]
I believe you have to run `cmake` from the `googletest` directory, not the `googletest/googletest` one.
The error you encounter happens because the variable `GOOGLETEST_VERSION` is not defined in the `CMakeLists.txt` file of the `googletest/googletest` directory.
It is defined in the `CMakeLists.txt` file of the `googletest` directory, however, and `cmake` should not give you that error if run in the correct directory.

**Comment by XavierAudier** [comment]
I believe you have to run cmake from the googletest directory, not the googletest/googletest one.
The error you encounter happens because the variable GOOGLETEST_VERSION is not defined in the CMakeLists.txt file of the googletest/googletest directory.
It is defined in the CMakeLists.txt file of the googletest directory, however, and cmake should not give you that error if run in the correct directory.

**Comment by nbatien1984** [comment]
[](https://www.facebook.com/watchparty/1707618836068325/)

**Comment by aquastripe** [comment]
> I believe you have to run cmake from the googletest directory, not the googletest/googletest one.
> The error you encounter happens because the variable GOOGLETEST_VERSION is not defined in the CMakeLists.txt file of the googletest/googletest directory.
> It is defined in the CMakeLists.txt file of the googletest directory, however, and cmake should not give you that error if run in the correct directory.

It works, thanks!
