### ISSUE TITLE
Add build install instructions to README.md

### ISSUE THREAD

**Issue by preetamsashankreddy** [google/googletest#2884]
It took a while to find the build commands which is not necessary for people interested in just using the library. These instructions will really save a lot of time for users and developers alike.

**Comment by oalpar** [comment]
can you tell me the build commands?

**Comment by falk-werner** [comment]
Are you looking for something like this:

1. make sure build tools and cmake are installed  
`sudo apt install build-essential cmake`
2. download and extract sources  
`wget https://github.com/google/googletest/archive/release-1.10.0.tar.gz`  
`tar -xf release-1.10.0.tar.gz`
3. compile  
`mkdir build`  
`cd build`  
`cmake ../googletest-release-1.10.0`
`make`
4. install   
`DESTDIR=/path/to/install make install`  
(I prefer installing it next to my current project. To install it globally you may use `sudo make install` instead, but I would not recommend it, since it will be hard to cleanup when you remove or update googletest.) 
5. cleanup  
`cd ..`
`rm -rf build googletest-release-1.10.0 release-1.10.0.tar.gz`

_Note that these instructions apply to Ubuntu an may differ on your platform._

There is a short note about build requirements in the [README.md](https://github.com/google/googletest#build-requirements), which says, you can use either [Bazel](https://bazel.build/) or [CMake](https://cmake.org/) to build the it from source.

**Comment by preetamsashankreddy** [comment]
Hi Falk,

Please find attached my patch that should address it at a basic level.You
can add other instructions as needed.

Regards,
Preetam

**Comment by CJ-Johnson** [comment]
Thank you for the Issue report. Are you able to attach a PR to this Issue?

**Comment by preetamsashankreddy** [comment]
I don't think I can. In any case, I do have issues with the basic turtle
example in gmock. I still doesn't link. It's wasting a lot of my time. Is
anyone willing to explain the issue ?

-Preetam

**Comment by derekmauro** [comment]
Can you please provide more details about exactly what problem you are running into?

**Comment by Aymkdn** [comment]
It seem the build instructions are missing in the README.

Thanks @falk-werner for giving some direction – I did the below:
> cd googletest-release-1.10.0/
> cmake .
> make
> sudo make install
