### ISSUE TITLE
Please add SaveArgReferee

### ISSUE THREAD

**Issue by sirzooro** [google/googletest#2946]
In my test I need to save address of object passed by reference to method, like in example below. I have looked for SaveArgReferee, but looks that it does not exists yet. Please add it.

```c++
#include <gmock/gmock.h>

using ::testing::_;
using ::testing::SaveArgReferee;

class Foo {};

class Bar
{
public:
    virtual ~Bar() {}
    virtual void func(Foo& foo) = 0;
};

class BarMock : public Bar
{
public:
    MOCK_METHOD1(func, void(Foo&));
};

TEST(BarTest, BarTest)
{
    BarMock mock;
    Foo* foo;
    EXPECT_CALL(mock, func(_)).WillOnce(SaveArgReferee<0>(&foo));
}
```

**Comment by sbenzaquen** [comment]
On Wed, Jul 15, 2020 at 10:49 AM sirzooro <notifications@github.com> wrote:

> In my test I need to save address of object passed by reference to method,
> like in example below. I have looked for SaveArgReferee, but looks that it
> does not exists yet. Please add it.
>
> #include <gmock/gmock.h>
> using ::testing::_;using ::testing::SaveArgReferee;
> class Foo {};
> class Bar
> {public:
>     virtual ~Bar() {}
>     virtual void func(Foo& foo) = 0;
> };
> class BarMock : public Bar
> {public:
>     MOCK_METHOD1(func, void(Foo&));
> };
> TEST(BarTest, BarTest)
> {
>     BarMock mock;
>     Foo* foo;
>     EXPECT_CALL(mock, func(_)).WillOnce(SaveArgReferee<0>(&foo));
> }
>
> You can implement actions like these with lambdas.

EXPECT_CALL(mock, func(_)).WillOnce([&](auto& v) { foo = &v; });

It is concise and doesn't require an ever expanding list of actions that
users have to remember.

**Comment by sirzooro** [comment]
@sbenzaquen: I know that I can use lambda for this. However this adds extra boilerplate code what makes it less readable (in my case I need lambda with 5 parameters). New action SaveArgReferee would make this more readable.

Personally I like gmock for offering many default matchers and actions - this makes tests more readable (and remember that code is read more often than it is written). I know that this comes with extra learning cost, but for me benefits outweight costs.

**Comment by asoffer** [comment]
I believe Sam's point is that there is a readability cost to adding this member. It's only useful if users know it's there, and having a long list of actions makes it more difficult. because no user can be expected to know the entirety of the list.

It's not that this action isn't useful, it's that extra matchers have a high bare for addition. even existing matchers probably wouldn't meet that bar. If we were starting over, we probably wouldn't have SetArgPointee either, we would do nearly everything with lambdas.

In this case, the lambda is not significantly longer. If you prefer a custom action, you can write one yourself.
