### ISSUE TITLE
I am getting a compilation error when I try to link a static library to my application

### ISSUE THREAD

**Issue by HardDie** [google/googletest#2980]
I use docker image: jenkins/jenkins

Project: https://github.com/HardDie/template_c_project

cmd:
```
git clone https://github.com/HardDie/template_c_project
cd template_c_project/tests
make
```

error:
https://pastebin.com/N38Jx4XM

gcc:
```
root@74222e2c14fe:~# gcc --version
gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

I tried with different versions of the gtest library: 1.5.0 - 1.10.0
I tried compiling a new gcc from this tutorial: https://linuxhostsupport.com/blog/how-to-install-gcc-on-debian-9/
Also I tried to explicitly pass the argument to gcc -std=c++11

**Comment by derekmauro** [comment]
Thank you for providing a full reproduction. You are seeing a multiple definition error because you are trying to compile all the source files.

gtest-all.cc is a file that includes all other source files <https://github.com/google/googletest/blob/master/googletest/src/gtest-all.cc>. You either have to compile gtest-all.cc only, or all source files, not including gtest-all.cc.

**Comment by HardDie** [comment]
Thank you!
