### ISSUE TITLE
Need to generate XML report in JUnit's format

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/googletest#30]
```
Google Test's XML report format differs from JUnit's slightly.  While we
cannot change it without breaking some existing processes, a quick
short-term solution is to write an XSLT to convert
Google Test's output to JUnit's format (it's also very flexible in
case JUnit changes its format).  In the long run, we could extend the
--gtest_output flag with an option to use the JUnit format, e.g.

 --gtest_output=junit_xml

instead of

 --gtest_output=xml

This will be more work to implement but is easier for the users.

```

Original issue reported on code.google.com by `shiq...@gmail.com` on 8 Sep 2008 at 7:20

**Comment by gayanpathirage** [comment]
Still not available; --gtest_output=xml still produce incompatible output. This is required for Jenkins, SonarQube like external analyzers. 

register  --gtest_output=junit_xml:output.xml
WARNING: unrecognized output format "junit_xml" ignored.

**Comment by KindDragon** [comment]
Jenkins xUnit support it https://wiki.jenkins-ci.org/display/JENKINS/xUnit+Plugin

**Comment by mbrucher** [comment]
But not everyone can use this plugin, unfortunately.
So this is quite bad...

**Comment by antekone** [comment]
Any news on junit_xml support?

**Comment by dhoer** [comment]
FYI, Jenkins has xunit plugin that converts googletest xml to junit format: https://plugins.jenkins.io/xunit/.

**Comment by KOLANICH** [comment]
Thanks, though I don't think it is very suitable for GitLab CI since it is written in Java and requires its runtime.

**Comment by albmiranda** [comment]
I also need a xml format compatible to SonarQube report.
Does anyone have any news?

**Comment by jasonmeverett** [comment]
Is there still no update on this??? Is Google Test still not producing JUnit XML output?

**Comment by KOLANICH** [comment]
I guess google doesn't use GitLab CI and SonarQube. So it won't output it ... unless any of you implemented it.

**Comment by schifazl** [comment]
I hope that this message is helpful. I used the converter_p3.py script from https://github.com/RedPaladin/sonar_test_report_converter

Using the script can be a bit tricky, as it requires regular expressions instead of simple glob patterns. This means that if you have multiple XML files, the command may inadvertently match files that you don’t intend.

In my case it was matching both the main test report file and its .xml.bak backup, so I added that `\$`. Anyway, in a CI context, this shouldn't be a concern.

I'm using it like this:

```
chmod +x .github/workflows/converter_p3.py
./.github/workflows/converter_p3.py -t gtest -D . -P gtest-test-results.xml\$ -o test-results.xml --gtest_src_folder path/to/test/sources --gtest_src_pattern .*\.cpp
```

Please note that the `-P` and `--gtest_src_pattern` are regular expressions. Modify as per your needs 😸
