### ISSUE TITLE
undefined reference link error using struct member variable(static const) wieh EXPECT_EQ

### ISSUE THREAD

**Issue by snoopspy** [google/googletest#3018]
Hi, all.
When struct(or class) member variable(static const) is used in EXPECT_EQ, it occurs "undefined reference" link error, meanwhile, it's Ok in EXPECT_TRUE.
Thanks in advance.

```cpp
#include <gtest/gtest.h>

struct Obj {
	static const int a = 1;
};

TEST(Obj, objTest) {
	EXPECT_TRUE(Obj::a == 1); // Ok
	EXPECT_EQ(Obj::a, 1); // undefined reference to `Obj::a'
}
```

[my-test.zip](https://github.com/google/googletest/files/5259972/my-test.zip)

**Comment by vslashg** [comment]
You are hitting a weird corner case of C++.  Your code above _declares_ the int Obj::a, but does not _define_ it.  (This is surprising because you provide the initializer value here.)

There are two possible fixes here:

1) provide a definition by putting the line `const int Obj::a;` inside a .cc/.cpp file in your program.
2) if you are using c++17 or later, write this declaration as `static constexpr int a = 1;` or `static inline const int a = 1;`.
