### ISSUE TITLE
Impossible to generate mock with a class that contains a method with [[nodiscard]] attribute.

### ISSUE THREAD

**Issue by Lorac** [google/googletest#3036]
Using GoogleMock 1.10 at 23b2a3b1cf803999fb38175f6e9e038a4495c8a5

```
class MyClass : public SomeInterface {
public:
    [[nodiscard]] bool isEmpty() const override;
};
```

It outputs something like this:
```
class MockMyClass : public MyClass {
    MOCK_METHOD(const nodiscard bool, isEmpty, (), (const, override));
};
```

The result doesn't compile.

**Comment by asoffer** [comment]
We don't support [[nodiscard]] or any other attribute on mock methods, in particular because MOCK_METHOD expands to two methods one of which should not get the attribute. You cannot put the nodiscard inside the MOCK_METHOD and the return type should be `bool` rather than `const bool`. With these changes everything seems to compile.

**Comment by Lorac** [comment]
@asoffer Maybe the google test mock generator should ignore any attributes?
