### ISSUE TITLE
CMake 3.19.0 throws deprecation warning in googletest/googletest/CMakeLists.txt:56

### ISSUE THREAD

**Issue by remyjette** [google/googletest#3040]
```
CMake Deprecation Warning at googletest/googletest/CMakeLists.txt:56 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.
```

**Comment by remyjette** [comment]
For more information, see https://cmake.org/cmake/help/git-master/release/dev/deprecate-policy-old.html

> * An explicit deprecation diagnostic was added for policy CMP0071 (CMP0071 and below were already deprecated). The cmake-policies(7) manual explains that the OLD behaviors of all policies are deprecated and that projects should port to the NEW behaviors.
>
> * Compatibility with versions of CMake older than 2.8.12 is now deprecated and will be removed from a future version. Calls to cmake_minimum_required() or cmake_policy() that set the policy version to an older value now issue a deprecation diagnostic.

**Comment by hyukmyeong** [comment]
All three CMakeLists.txt before https://github.com/google/googletest/pull/674 are shown with the same version as the minimum constraint.

And the current content seems to have been applied from https://github.com/google/googletest/pull/1682

In each case, when a new function needs to be applied, it seems that it was upgraded little by little.
Even now, the versions applied to the three CMakeLists.txt are different

However, as you shared, it seems very fair to apply 2.8.12 to all three CMakeLists.txt because versions earlier than 2.8.12 are already deprecated

**Comment by zaphodikus** [comment]
Is, it possible to simply update the quick start guide itself on google.io, either to point to the latest release in the quick start guide steps, or to add a comment in there about how to grab the latest release archived .zip path?
