### ISSUE TITLE
Updated StreamPrinter in gtest-printers.h breaks enum operator>> templates

### ISSUE THREAD

**Issue by ChrisAWills** [google/googletest#3126]
Commit: 0555b0eacbc56df1fd762c6aa87bb84be9e4ce7e  changed the way the StreamPrinter works and is causing our code to now fail to compile.  Before this change the functions worked as expected and the code would compile.  

The issue is that we have a templated function to output the value from scoped enums using a operator<< overload with ostream&.  It works fine when the enum is in the same namespace as the template but will fail if it is in a separate namespace.  

Short sample code showing the issue can be found at https://godbolt.org/z/sGE5sf

If the line "void operator<<(LookupBlocker, LookupBlocker);" is removed our code will compile.

What needs to change so that the code will compile?   Surprisingly it compiles fine on latest vs2019 but fails with gcc even though on godbolt it fails to compile in both cases.

**Comment by sbenzaquen** [comment]
On Sat, Nov 21, 2020 at 12:41 AM Chris Wills <notifications@github.com>
wrote:

> Commit: 0555b0e
> <https://github.com/google/googletest/commit/0555b0eacbc56df1fd762c6aa87bb84be9e4ce7e>
> changed the way the StreamPrinter works and is causing our code to now fail
> to compile. Before this change the functions worked as expected and the
> code would compile.
>
> The issue is that we have a templated function to output the value from
> scoped enums using a operator<< overload with ostream&. It works fine when
> the enum is in the same namespace as the template but will fail if it is in
> a separate namespace.
>
> Short sample code showing the issue can be found at
> https://godbolt.org/z/sGE5sf
>
> If the line "void operator<<(LookupBlocker, LookupBlocker);" is removed
> our code will compile.
>
This is working as intended.
operator<< is meant to be found by ADL (
https://en.cppreference.com/w/cpp/language/adl), which is why it works when
the operator is defined in the right namespace.
The blocker function is there to prevent misuse that can lead to brittle
code and ODR violations (both we have seen in the past).
The "catch-all" operator defined in that compiler explorer link is one that
can easily lead to ODR violations. Very subtle things like order of
#includes, or having certain unrelated includes in your transitive
dependency, could lead to undefined behavior.

If the universal printer is missing something that it should be able to
handle, then we can see into adding it.

**Comment by ChrisAWills** [comment]
So if I move the template into the same namespace as the Enums it should work.  I will give that a try though it means I would need to have multiple copies of the same template for each namespace that has an Enum that I want to use that operator for.

**Comment by sbenzaquen** [comment]
On Mon, Nov 23, 2020 at 12:43 PM Chris Wills <notifications@github.com>
wrote:

> So if I move the template into the same namespace as the Enums it should
> work. I will give that a try though it means I would need to have multiple
> copies of the same template for each namespace that has an Enum that I want
> to use that operator for.
>
To avoid ODR violations it has to be in the same namespace and file that
declares the type.
But since this is a catch-all function it is really hard to have it in the
right place.

How exactly are you trying to print these enums in a generic way?
Could this be something done directly in googletest?

**Comment by ChrisAWills** [comment]
Its just outputting the underlying integer values assigned to the enums for debug and logging purposes in most cases.  The reason it showed up was that I am comparing enums as part of the testing and that triggered the compilation error.

Moving the operator<< into my enum namespaces worked to get around the error and I noticed I only needed it in 2 spots so was not that bad for me to do.
