### ISSUE TITLE
support QuickCheck-style declarative random tests

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/googletest#320]
```
QuickCheck (http://en.wikipedia.org/wiki/QuickCheck) is a widely-used Haskell 
library for writing very-high-level test assertions about the properties of a 
piece of code, and the assertions will be verified by randomly generated test 
data.  The user can declaratively control the generation of the random data.

This style of testing can greatly complement what gtest already offers, and 
significantly increase test coverage with little code.

There is a C++ implementation at http://software.legiasoft.com/quickcheck/, but 
that's more of a prototype than a mature library.  We should carefully think 
through the design in the context of C++ rather than doing a quick port from 
Haskell.


```

Original issue reported on code.google.com by `w...@google.com` on 28 Sep 2010 at 7:05

**Comment by skhoroshavin** [comment]
Hello. I'm interested in implementing property-based testing utility in Google Test. One of my main concerns are that in order to implement shrinking properly I need to "sandbox" intermediate test runs so that assertions don't litter output and preferably not influence test statistics. As far I as I see there is no such mechanism in gtest, so I need to implement it. Before undertaking this task I'd prefer to know if such change have any chance to be accepted.

I know there is rapidcheck, but it has several drawbacks (at least from my point of view):
- gtest asserts cannot be used inside it's properties
- compiler support is somewhat flaky (for instance it doesn't compile with gcc 4.8, which is default on Ubuntu 14.04, and there are much more such examples)
- personally I don't like it's shrinking system very much, python's hypothesis approach looks much more interesting

**Comment by gennadiycivil** [comment]
Thank you very much for this report. The best way to approach this would be to create a proper PR and submit it for consideration.

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you
