### ISSUE TITLE
Callout Notes aren't properly rendered on GitHub

### ISSUE THREAD

**Issue by fpezzino** [google/googletest#3301]
**Describe the bug**

This string appears on some documentation when viewed on GitHub from a browser.

`{: .callout .note}`

For example:
[Explicit Success and Failure](https://github.com/google/googletest/blob/e7e591764baba0a0c3c9ad0014430e7a27331d16/docs/advanced.md#explicit-success-and-failure) Third paragraph
[Beware of the nomenclature](https://github.com/google/googletest/blob/d9c309fdab807b716c2cf4d4a42989b8c34f712a/docs/primer.md#beware-of-the-nomenclature) First paragraph

**Additional context**

Probably related to https://github.com/google/googletest/issues/2938#issuecomment-658242757

**Comment by tony955084** [comment]
https://shopee.tw/product/4778468/2316179947?smtt=0.293761175-1614967009.9

**Comment by ericschmidtatwork** [comment]
Thanks for the bug and good catch linking it to #2938. This is indeed caused by differences in Markdown rendering engines. We're currently updating the docs to use [GitHub Pages](https://google.github.io/googletest/), where these callouts are rendered correctly (see [Explicit Success and Failure](https://google.github.io/googletest/advanced.html#explicit-success-and-failure)).

Going forward we recommend reading the docs on the GitHub Pages site and not in the GitHub browser - we'll work on surfacing the site better in the READMEs, etc.
