### ISSUE TITLE
i get this question when i build gtest in Android Studio with my windows computer。

### ISSUE THREAD

**Issue by Ljy545733599** [google/googletest#3303]
exception while building Json C:\Users\wb.linjunyi\AndroidStudioProjects\rheia_android\library\.cxx\cmake\debug\arm64-v8a\googletest-src\.git\objects\pack\pack-d7c671c3cc55a7d5122e61ec17261bca32c7e65b.idx

how can i fix it？

**Comment by ssabawissabawi** [comment]
https://core.telegram.org/api

**Comment by tony955084** [comment]
https://shopee.tw/product/8698831/1217604708?smtt=0.293761175-1614965437.9

**Comment by derekmauro** [comment]
While we need more information to understand what the issue is, we think this is unlikely to be an issue with GoogleTest and is more likely to be an issue with your setup. See if you can find a similar issue on a forum specific to Android Studio. If you still have an issue and can provide us with full reproduction steps, feel free to re-open this issue.
