### ISSUE TITLE
ASSERT_ macros cannot be used within coroutines

### ISSUE THREAD

**Issue by Tradias** [google/googletest#3353]
**Describe the bug**

Using any `ASSERT_` macro in a `TEST/TEST_` within a coroutine cannot be compiled.

**Steps to reproduce the bug**

https://godbolt.org/z/qehMoT7dx

```c++
#include <gtest/gtest.h>

#include <boost/asio.hpp>
#include <boost/asio/co_spawn.hpp>

TEST(Coroutine, test) {
  boost::asio::io_context io_context;
  boost::asio::co_spawn(
      io_context,
      []() -> boost::asio::awaitable<void> {
        ASSERT_TRUE(true);
        co_return;
      },
      boost::asio::detached);
  io_context.run();
}
```

Error message (GCC 10.2):
```
<source>:11:9: error: could not convert 'testing::internal::AssertHelper(testing::TestPartResult::kFatalFailure, ((const char*)"<source>"), 11, testing::internal::GetBoolAssertionFailureMessage(const testing::AssertionResult&, const char*, const char*, const char*)(((const char*)"true"), ((const char*)"false"), ((const char*)"true")).std::__cxx11::basic_string<char>::c_str()).testing::internal::AssertHelper::operator=(testing::Message())' from 'void' to 'boost::asio::awaitable<void>'
   11 |         ASSERT_TRUE(true);
      |         ^~~~~~~~~~~
      |         |
      |         void
<source>:10:7: error: a 'return' statement is not allowed in coroutine; did you mean 'co_return'?
   10 |       []() -> boost::asio::awaitable<void> {
      |       ^
```

Error message (MSVC x64 19.28.29913):
```
[build] : error C3773: Use of 'return' in this context is a non-conforming extension in C++20
[build] : note: Please use '/await' command-line option to enable relevant extensions
```

**Does the bug persist in the most recent commit?**

Yes, using commit 6a5eb807493214be733d4cbb9f07f22fde25284f from master

**What operating system and version are you using?**

For the MSVC x64 19.28.29913 error I am using Windows Version 10.0.19042 Build 19042

**What compiler and version are you using?**

GCC 10.2   
MSVC x64 19.28.29913

**What build system are you using?**

CMake 3.20.0    
Ninja 1.10.2

**Comment by asoffer** [comment]
ASSERT macros hide a `return` statement. As a best practice, we generally suggest only using them directly in a TEST, otherwise they do not have the intended behavior (stopping the remaining execution of the test). This is the case for function calls, callbacks, coroutines, etc. Unfortunately there's no way to hook into the call infrastructure to propagate the fact that an ASSERT was called through multiple layers back up to the top layer (exceptions could be used to get some of this, but not all, and we also need to support -fno-exceptions builds anyway).

As an alternative, we suggest having the coroutine return some value on which the TEST can ASSERT.
