### ISSUE TITLE
Hierarchical Grouping

### ISSUE THREAD

**Issue by image357** [google/googletest#3438]
**Describe the bug**

There is no hierarchical grouping of tests.

**Steps to reproduce the bug**

Use googletest with a big, non-flat, project and find yourself in test structuring hell.

**Does the bug persist in the most recent commit?**

yes

**What operating system and version are you using?**

all

**What compiler and version are you using?**

all

**What build system are you using?**

all

**Additional context**

This is seriously needed. You should not organize tests in a flat structure for huge projects. This is a problem for display and filtering of tests. And the most natural name seperator `_` is forbidden in tests. So there is even no clean visual way of grouping tests hierarchical by name.

See also #2080

**Comment by image357** [comment]
btw. I would assist in implementing this, if someone could give me a short rundown on the project structure, layout and rationale.

**Comment by derekmauro** [comment]
I'm not 100% sure what you are asking for here. Can you further explain what you'd like to see?

**Comment by image357** [comment]
Something like TestSuites that contain other TestSuites and not only Tests. I'm thinking of something like a Composite Pattern.

**Comment by derekmauro** [comment]
At Google we have a giant monorepo and we solve this problem using the directory structure and smaller individual test programs to achieve a tree layout.

Unfortunately this isn't a feature we've seen demand for. Because this would be a large infrastructure change and because we already have a working solution we can't commit resources to implementing this.

**Comment by image357** [comment]
uhm ... I would do it. question is: would you want it in your repo?
