### ISSUE TITLE
Release build error v1.8.x on IBM ILE C/C++ 7.4 compiler

### ISSUE THREAD

**Issue by d7d1cd** [google/googletest#3566]
**Problem**
I get the following compilation errors when I try to compile the src/gtest-all.cc file:

```
gtest/internal/gtest-port.h (2488):
The name lookup for "isatty" did not find a declaration.

src/port.cc (1034):
The name lookup for "mkstemp" did not find a declaration.
```

**Decision (bad)**
To solve the problem, I replaced the isatty function by simply returning the number 1:
`inline int IsATTY(int fd) {return 1; }`

And for another error I did the following:
`const int captured_fd = 1;`

After that, the code was compiled. Several unit tests passed successfully.

**System**
I didn't use the build system, but just compiled src/gtest-all.cc from the command line. I did not declare any macros. Operating system IBM i 7.4 (OS/400).

**Question**
Despite the fact that the framework code after the edits was compiled and launched, it is obvious that the edits are incorrect. How to make the correct edits and what are the risks of using the framework with my edits (probably some functionality will not work)?

**Comment by derekmauro** [comment]
Unfortunately we don't support this compiler.

As for your questions though, I believe everything will mostly work. It looks like `int IsATTY(int fd)` is only used for determining if GoogleTest should use colored output. It might be better to return 0 instead of 1 in that case. From a quick scan, `mkstemp` appears to only be used to test GoogleTest, so I think your edit there is probably an ok hack to get things working.
