### ISSUE TITLE
Can't implement a printer for 128 bit GCC integers

### ISSUE THREAD

**Issue by Silicomancer** [google/googletest#3595]
I tried to provide overloads that correctly print GCC 128-bit integers (`__int128_t` and `__uint128_t`) in google test error output.

The following test will fail as expected but it will print a nasty wrong integer:
```
    __uint128_t a = ((static_cast<__uint128_t>(0x89898989'ABABABABull)) << 64u) + 0xCDCDCDCD'EFEFEFEFull;
    __uint128_t b = 0;
    EXPECT_EQ(a, b);
```
      
I tried to implement a `PrintTo` overload but it is not used (while similar overloads work fine for custom types):
`    void PrintTo(const __uint128_t& pValue, ::std::ostream* pOs);`
   
I also tried an operator overload:
`    std::ostream& operator <<(std::ostream& pOut, const __uint128_t& pValue) noexcept;`

I get an errors for this: 
`    "error: no matching function for call to ‘testing::internal::internal_stream_operator_without_lexical_name_lookup::StreamPrinter::PrintValue(const __int128 unsigned&, std::nullptr_t)’"`
This is serious problem since existing overloads can collide with google test!

How can I let Google Test print 128 bit integers correctly?

**Comment by sbenzaquen** [comment]
It seems that `__uint128_t` does not have `operator<<`, and it is using our fallback for "integrals" by being implicitly converted to `int64_t` first.
Unfortunately, there is no right place for a user to put a PrintTo or operator<< overload for `__uint128_t`. ADL won't work with this type because it has no associated namespace. The only place where it can work is putting it in `gtest-printers.h` in the `testing::internal` namespace.

Adding PrintTo overloads in `gtest-printers.h` for `__uint128_t` and `__int128_t` should be simple. Are you interested in sending a patch? If not, we can look into it.

**Comment by Silicomancer** [comment]
Thanks a lot for you fast and helpful reaction!
It would be great if you could have a look...
