### ISSUE TITLE
Use of None in Google Test conflicts with a preprocessor definition in X11/X.h

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/googletest#371]
```
X11/X.h #defines None, which breaks compilation of gtest-type-util.h if gtest.h 
is #included after X.h.
```

Original issue reported on code.google.com by `vladlosev` on 2 Jun 2011 at 8:23

**Comment by qzole** [comment]
We bumped into to issue too. Would undefining and redefining them be a good solution? Or would simply undefining them and leaving them like that? (Since if Bool is left defined to int, as it is in X.h, it prevents its usage in client code).

Redefinition could be done with `#pragma push_macro` and `#pragma pop_macro`, but they are non-standard. I don't know it that would be a problem?

I'll try to fix this in X11 side, don't know if they would accept a patch that undefines these defines since that could be seen as breakage of public API. (A workaround would be still nice in gtest, so it can work properly with older X11 headers)

**Comment by jasjuang** [comment]
Bumped into this issue too. Would be great to see a fix

**Comment by BillyDonahue** [comment]
It's an internal placeholder struct. We can call it whatever we want, so
maybe this is an easy one.
Anyone want to send a PR for it?
