### ISSUE TITLE
Xml Generation from Google test does not show skipped test cases

### ISSUE THREAD

**Issue by satishsingh0077** [google/googletest#3837]
I have few test cases which i have disabled using DISABLED_ before test name and some tests are skipped using GTEST_SKIP(). This is working fine and i can see the tests being disabled and skipped in the teminal log. The problem is when i am generating the xml file from the test.
`--gtest_output=xml:/data/TestReport.xml`
The generated XML
`<?xml version="1.0" encoding="UTF-8"?>`
`<testsuites tests="17" failures="7" disabled="3" errors="0" time="57.713" timestamp="T10:31:55" name="AllTests">`
`<testsuite name="UNITTEST" tests="17" failures="7" disabled="3" errors="0" time="45.713" timestamp="T10:32:04">`
`<testcase name="Test_1" status="run" result="skipped" time="0" timestamp="T10:32:04" classname="UNITTEST" />`
`<testcase name="Test_2" status="run" result="completed" time="0.461" timestamp="T10:32:04" classname="UNITTEST" />`
`<testcase name="Test_3" status="run" result="completed" time="7.089" timestamp="T10:32:05" classname="UNITTEST">`

I would like to point out that the tag testsuites which is a consolidation of all the testsuite does not have an attribute skipped. The tag testsuite which is a consolidation of all the tests also does not have the attribute skipped. However, the test Test_1 does show the result as skipped. Is there any configuration to make the count of skipped appear.

**Comment by dinord** [comment]
GoogleTest should print the number of skipped tests as part of the XML report: https://github.com/google/googletest/blob/5126f7166109666a9c0534021fb1a3038659494c/googletest/src/gtest.cc#L4319

Since this sounds like a possible bug, would you mind re-opening the issue using the "Bug report" template and providing answers to questions from that template?
In order to debug this issue, we need to be able to reproduce it.

**Comment by satishsingh0077** [comment]
I have already opened the ticket here. https://github.com/google/googletest/issues/3836
