### ISSUE TITLE
Potential memory problem of TEST_P mode in unit testing

### ISSUE THREAD

**Issue by yi1zhao** [google/googletest#3857]
Hello. This Issue is about the potential memory problem of `TEST_P` mode in unit testing.
Of course, the function of `TEST_P` mode is OK. The potential memory problem means that the memory occupation may increase with the increase of test cases. 

**Describe the proposal**

The function of `TEST_P` is convenient, it first collects all prepared data with `::testing::ValuesIn(cases)`. However, it will first allocate memory of N test cases, then run N test cases, and finally destroy N memory, that is (N malloc - N running - N free). Instead of first allocate memory of a test case, then running a test case, and destroying a memory, repeating this N times, that is (N repeats of 1 malloc - 1 running - 1 free). The current `TEST_P` mode or architecture may run out of memory when there are many test cases.

It would be better if it could be improved, thank you very much.

**Comment by asoffer** [comment]
Thanks for reporting this. I do not think this is something we are going to address. If you are having specific concrete memory problem due to test case construction, we may look at those cases, but I would generally suggest breaking up the test cases into multiple `ValuesIn`, or possibly multiple test binaries if necessary.
