### ISSUE TITLE
bugprone-exception-escape clang-tidy check reported for every noexcept MOCK_METHOD

### ISSUE THREAD

**Issue by PiotrNycz** [google/googletest#4034]
Consider this simple code https://godbolt.org/z/rdT4abhvv

```
#include <gtest/gtest.h>
#include <gmock/gmock.h>

struct Foo {
    MOCK_METHOD(void, foo, (), (noexcept));
};

TEST(MyTest, aaa) {
    Foo foo;
    EXPECT_CALL(foo, foo());
    foo.foo();
}

int main(int argc, char*argv[]) {
  ::testing::InitGoogleTest(&argc, argv);
  return RUN_ALL_TESTS();
}
```

For every `MOCK_METHOD(... (noexcept))` clang-tidy check bugprone-exception-escape is reported:
```
<source>:5:23: warning: an exception may be thrown in function 'foo' which should not throw exceptions [bugprone-exception-escape]:
    MOCK_METHOD(void, foo, (), (noexcept));
                      ^
```

This is somehow expected - but really annoying to add for every noexcept mocked method `NOLINTNEXTLINE(bugprone-exception-escape)`

I can see two solutions:

1. If, in macro MOCK_METHOD, it is detected that function is "noexcept" -- use noexcept functions in function body, or add extra try-catch

2. Allow users to specify some GMOCK_NOEXCEPT_MOCK_METHOD_EXTRA_COMMENT. I mean to allow to speficy in users code:
````
#define GMOCK_NOEXCEPT_MOCK_METHOD_EXTRA_COMMENT NOLINT(bugprone-exception-escape)
````
And put this comment, wrapped with /**/ inside MOCK_METHOD definition.

This we started to see from version 1.12.1. In previous versions it was not reported - I have no idea why it was not reported in previous versions,

**Comment by asoffer** [comment]
Thanks for raising this issue. I don't think we are going to support, primarily because the semantics of `noexcept` are confusingly subtly different. `noexcept` doesn't mean "exceptions cannot be thrown inside me." It means "the caller will not see an exception thrown from inside me." The distinction is exceptions can happen inside a `noexcept` function, but they might abort execution.

The following valid (albeit strange) code would break if we were to mark these functions as noexcept:
```
EXPECT_CALL(foo, foo()).WillOnce([] { throw "something"; });
EXPECT_DEATH({ foo.foo(); });
```

Beyond this, because users can specify arbitrary code to execute inside the mock, we don't really have a good way to enforce noexcept the whole way down (at least not until C++17 where `noexcept` becomes part of the type signature).

**Comment by PiotrNycz** [comment]
Yes, true, with `EXPECT_CALL(foo, foo()).WillOnce(testing::Throw("something"));` it should be death test, unless, AFAIR, own terminate will be installed in the program. I did not want to change that. So my option/proposal #1 was not, to some extent, valid approach. 

For my second option - actually we might define own macro for noexcept methods -- with this extra NOLINT added inside. Or just write this extra line with NOLINTNEXTLINE in every such case.

**Comment by dbolduc** [comment]
is it worth adding a note about the clang tidy warning to this section of the cookbook: https://chromium.googlesource.com/external/github.com/google/googletest/+/HEAD/docs/gmock_cook_book.md#mocking-destructors
