### ISSUE TITLE
Checksum for https://github.com/google/googletest/archive/refs/tags/release-1.8.1.tar.gz changed

### ISSUE THREAD

**Issue by rachelstowell** [google/googletest#4135]
### Describe the issue

For this release:

https://github.com/google/googletest/archive/refs/tags/release-1.8.1.tar.gz

We had an md5sum of 2e6fbeb6a91310a16efe181886c59596

As of today, this changed to e864f1ccccf8cd722ad711c7828890f2 

Was this an intended change?

### Steps to reproduce the problem

Download release, check md5sum

### What version of GoogleTest are you using?

1.8.1

### What operating system and version are you using?

Ubuntu 22.04

### What compiler and version are you using?

n/a

### What build system are you using?

n/a

**Comment by derekmauro** [comment]
It wasn't changed by us. This issue is actually a good example of [Hyrum's Law](https://www.hyrumslaw.com/).

https://github.com/spack/spack/issues/5411 is another report of this:
> _Short story:_ GitHub has changed the way they generate their release "archives". They're generated dynamically so many checksums have changed for `github.com/.../archive/` URLs. Looks like we may have to download all these tarballs and re-checksum them.

You can imagine, for example, that GitHub decided to change the compression level of the archives. This would change the checksum. The archives would still have the same contents, but the compressed bytes returned would not be the same.
