### ISSUE TITLE
[FR]: Make GetParam() into a constexpr

### ISSUE THREAD

**Issue by BadgerKing7** [google/googletest#4312]
### Does the feature exist in the most recent commit?

No

### Why do we need this feature?

Currently, `GetParam()` cannot be used to give template arguments to template classes/functions in parametrized tests. This means that tests have to be duplicated even if the only difference is the template argument.

### Describe the proposal.

Make `GetParam()` and `parameter_` constexpr.

### Is the feature specific to an operating system, compiler, or build system version?

No

**Comment by dinord** [comment]
Currently `GetParam` is not `constexpr` by design, as parameters can be constructed at runtime.

For giving template arguments, use [typed tests](http://google.github.io/googletest/advanced.html#typed-tests) (i.e. `TYPED_TEST` or `TYPED_TEST_P`, depending on the use case).

Here's an example that uses `TYPED_TEST` to inject `constexpr` value parameters into a test: https://godbolt.org/z/cTaGdMMzK

Please re-open the issue if I missed something.
