### ISSUE TITLE
[FR]: Is it possbile to add a public API to reset g_argvs? (g_argvs.clear())

### ISSUE THREAD

**Issue by nehasharan** [google/googletest#4320]
### Does the feature exist in the most recent commit?

No

### Why do we need this feature?

I have an application where I am running google test in the background thread in the application. Now I need to run several tests with different filters in the same session of the app. To change the filters, one need to change the g_argvs or use GTEST_CUSTOM_GET_ARGVS_ but then I will have to change the code in googletest repo. (gtest.cc/custom/gtest.h) I don't want to make application specific change in googletest repository as I want to keep it a direct mirror of the public repository for future maintenance. Is there a possibility of exposing a public Api to reset the g_argvs as this is the way to pass the filters before running the test?

### Describe the proposal.

There are some solutions from google like using "GTEST_CUSTOM_GET_ARGVS_" but for this I will have to make changes in gtest.cc or #include "gtest/internal/custom/gtest.h" which are not the desired solutions.

### Is the feature specific to an operating system, compiler, or build system version?

No

**Comment by derekmauro** [comment]
This request is for a particular solution (resetting argv) when the problem may have a different solution, for example, an API to manually specify which tests are run. It is unlikely that we are going to implement this.

If you are trying to parallelize your tests, we recommend that sharding approach: https://github.com/google/googletest/blob/main/docs/advanced.md#distributing-test-functions-to-multiple-machines

**Comment by nehasharan** [comment]
Hi @derekmauro, what I need is to call RUN_ALL_TESTS() more than once (sequentially, not in parallel) in the same process, with potentially different arguments. Right now we can't do that since InitGoogleTests will do nothing if called a second time.

**Comment by martinerikwerner-aac** [comment]
I have also ran into same non-supported use-case as described here, where I would like to be able to run gtest multiple times, with different command line flags, from the same process.

In my case specifically this is on an embedded RTEMS system, which is "a single process, multi-threaded execution model". This seems to make the state of gtest persist throughout the whole system, even if RUN_ALL_TEST() has run to completion.

In practice, as far as I can tell, this means that once I have called `testing::InitGoogleTest()` I need to power-cycle the system in order to be able to run gtest again with different command line flags.

Exposing a way to clear g_argvs as suggested seems to be a low-level way to achieve this, but alternatively adding something like `testing::ReInitGoogleTest()` which forces re-initialization, or potentially even modifying the behaviour of `testing::InitGoogleTest()` so that instead of being a no-op if called more than once, it does re-init each time, sounds like possible solutions for this use-case.

Is there a particular reason why gtest is actively disallowing running the initialization code multiple times?:
https://github.com/google/googletest/blob/b75ecf1bed2fcd416b66c86cb6fe79122abf132e/googletest/src/gtest.cc#L6787-L6788

**Comment by martinerikwerner-aac** [comment]
After digging some more, it seems like just clearing g_argvs is far from enough to allow re-initialisation, since quite a few of the internals assume and/or enforce only being executed once, for example:

`internal::g_help_flag`
`UnitTestImpl::post_flag_parse_init_performed_`
(and likely more?)

I initially tried injecting:
```
#define GTEST_CUSTOM_INIT_GOOGLE_TEST_FUNCTION_(argc, argv) \
  do {                                                      \
    internal::g_help_flag = false;                          \
    internal::g_argvs.clear();                              \
    internal::InitGoogleTestImpl(argc, argv);               \
  } while (0)
```
via the preprocessor `-imacros` flag when compiling gtest (which avoids modifiying the gtest sources themselves). But `UnitTestImpl::post_flag_parse_init_performed_` (and others?) are not accessible here, so this still becomes a hacky half-baked re-initialization which seems to work for some things but not for others (and is probably a very bad idea).
