### ISSUE TITLE
Print "Failure" on a single line, possibly optional?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/googletest#468]
```
It would be nice to be able to print failures on a single line so that error 
lists on some IDE's also display the test failure text and not just "Failure".

What steps will reproduce the problem?
1. run a test that fails (gtest built using using gcc)
2. observe output in Eclipse.

gtest-1.7.0

In the function TestPartResultTypeToString, either remove the newline from 
"Failure\n" or offer a command line option that controls this to avoid breaking 
any tools that rely on current behaviour.

I tried to resolve this by providing and alternative function that was in the 
'internal' namespace but that results in ambiguity due to ADL.

```

Original issue reported on code.google.com by `pw.banni...@googlemail.com` on 16 Jul 2014 at 3:39

**Comment by nioncode** [comment]
Is this something that might have a chance to become available or should we use `TestEventListener` instead?

**Comment by gennadiycivil** [comment]
Thank you very much for this report. The best way to approach this would be to create a proper PR and submit it for consideration.

**Comment by nioncode** [comment]
Actually, after further investigation it seems like it would be better to simply indent all information belonging to one assertion error by at least 1 space.
Most error parsers (e.g. QtCreator's) capture everything following a `file:lineNumber: error message` line if it is indented. E.g. that's how clang's errors get captured in QtCreator as well.

For reference, here is my current `TestEventListener` that modifies the output to be parsed correctly in QtCreator:
```c++
    virtual void OnTestPartResult(const TestPartResult& result)
    {
        if (!result.failed()) {
            return;
        }
        std::string summary(result.summary());
        // Indent each line of the summary to make QtCreator parse
        // the additional information and display it when viewing
        // the failure in the 'issues' list.
        std::string indentedSummary("  ");
        for (auto c : summary) {
            indentedSummary += c;
            if (c == '\n') {
                indentedSummary += "  ";
            }
        }

        fprintf(stdout,
                "%s:%d: Test Failure\n%s\n",
                result.file_name(),
                result.line_number(),
                indentedSummary.c_str());
        fflush(stdout);
    }
```

Does adding extra whitespace in front of each line (except the line containing the erroneous source code line) break any existing behavior? It even looks a bit tidier on `stdout` imo.

**Comment by nioncode** [comment]
Which editor is this? How does it handle compiler errors that span multiple lines?

**Comment by nioncode** [comment]
Today, the multi-line issue reporting in QtCreator broke again for my gtest suite. Turns out, QtCreator uses different parsers for the error messages depending on which compiler you use. My snippet from above works fine for the GCC error parser, but not for Clang's.
For Clang, an additional  `0: error: ` is needed after the line number. Also, to prevent QtCreator from attaching everything up to the next error to the first issue, we have to add a summary line after each test.

Below is my current `TestEventListener` that works for both, GCC and Clang in QtCreator:
```C++
    virtual void OnTestPartResult(const TestPartResult& result)
    {
        if (!result.failed()) {
            return;
        }
        std::string summary(result.summary());
        // Indent each line of the summary to make QtCreator parse
        // the additional information and display it when viewing
        // the failure in the 'issues' list.
        // In fact, this only works for the GCC error parser. For Clang, the
        // summary does not need to be indented.
        std::string indentedSummary("  ");
        for (auto c : summary) {
            indentedSummary += c;
            if (c == '\n') {
                indentedSummary += "  ";
            }
        }

        // QtCreator's Clang error parser only parses issues that have the word
        // 'error' in them and contain the character position (here fixed to 0)
        // of the error.
        fprintf(stdout,
                "%s:%d:0: error: Test Failure\n%s\n",
                result.file_name(),
                result.line_number(),
                indentedSummary.c_str());
        fflush(stdout);
    }

    virtual void OnTestEnd(const TestInfo& test_info)
    {
        if (test_info.result()->Failed()) {
            // QtCreator's Clang error output parser parses everything between
            // the start of the error / warning and either a) the next start of
            // an error / warning, or b) a summary in the form of
            // '%d error generated.'. To satisfy the parser, we simply print
            // a summary after each failed test case.
            fprintf(stdout, "1 error generated.\n");
            fflush(stdout);
        }
        eventListener->OnTestEnd(test_info);
    }
```

In light of these findings, it might not make much sense to try to make test assertions behave like compiler errors and simply go with the original proposol to print failures in a single line. I played around with this initially, but found error messages on one line too chaotic, because they contained too much information.

Even with a simple example like below it gets tricky to format it nicely on a single line:
```
../test_abc.cpp:65: Failure
      Expected: 0
To be equal to: numCalls
      Which is: 1
```
```
../test_abc.cpp:65: Failure. Expected: 0 To be equal to: numCalls Which is: 1
```
Does not read very nice. With more knowledge of the individual assertion it could be formatted in a different way, but depending on the assertion (equals, greater than, ...) this might just get messy really fast.

The only sensible way would be to just print the test case name in the summary line to get an idea which test cases broke. For more details, it would still be necessary to check the compilation output.

**Comment by gennadiycivil** [comment]
I am closing this issue. There is a lively discussion but no PR
