### ISSUE TITLE
gmock git repository is of limited use without a gtest submodule

### ISSUE THREAD

**Issue by BillyDonahue** [google/googletest#513]
_From @obruns on August 25, 2015 7:42_

[I had opened this issue as #181 at 2015-08-24 8:15 PM UTC but the project has been regenerated in the meantime; my considerations wrt. breaking existing users may not apply ;)]

Unit test frameworks are a prime example for Git submodules: You depend on the code, yet it is unlikely you'll ever change it. All you do is pulling in a newer version of the foreign code whenever you see the need for it - so why version the entire third party code when you can maintain just the SHA-1?

Unfortunately the above cannot be done with this gmock repository due to the unmet gtest dependency.
Ideally, at least the 1.7.0 tag (and all commits thereafter) have gtest added as a submodule. Yes, this means altering history but I think it is justified for the following reasons:
- the repo clone is less than a week old; the announcement on the mailing list has been made within the past 48 hours. Hence rewriting history won't break too many users
- making the submodule available to a long-time stable release (1.7.0) helps conservative users that would not jump to a 1.8.0 release anytime soon

Suggested procedure:
- take down the repository or add a warning about changes to the history
- rewrite the commit pointed to by the 1.7.0 tag so that the gtest/ subdirectory is a submodule
- test all commits since (and including) that 1.7.0 one
- re-create the 1.7.0 tag (--force)
- force-push the rewritten history

This would be the absolute minimum. Ideally, all 1.x tags would get such treatment (as time permits).

Related: #180 (lost when the project was regenerated; it illustrated how the unmet gtest dependency confuses users, similar to what Alex Shaver says on the mailing list (link below))
Related: https://groups.google.com/d/msg/googlemock/UD3nRr3RAQk/tj-R2A9UCAAJ

_Copied from original issue: google/googlemock#178_

**Comment by obruns** [comment]
Hi @BillyDonahue,

I learned from #510 that your primary intention to merge gmock with gtest is to ease development. Given the history of gmock (frequent updates to the svn:externals property) this seems to be the obvious decision. 

Unfortunately, the way the two repositories were merged, does not allow to use a release state (i.e. tag; see my original message above). I have created a script [1] that rebuilds the svn:external dependency from gmock to gtest using a submodule. The final gmock repository can be found at [3]. The gtest repository clone it depends on is at [2]. The script does more than I originally described in 'Suggested procedure' above - the relationship is made throughout the entire history of gmock, not just the 1.7.0 tag.

Note that your work with merging the two repos and my work on the history do not obviate each other. Rather, the recent work you made could be rebased onto an improved history.

Should this be interesting to you, please have a look at the TODO items I left in `gmock-with-gtest-submodule.sh` - I'd be willing to address them if you think this is worth being pursued.

[1] https://github.com/obruns/create-gmock-with-gtest-submodule
[2] https://github.com/obruns/gtest
[3] https://github.com/obruns/gmock

**Comment by BillyDonahue** [comment]
This is impressive work. I'm nervous about writing to the git history, though.
Is it really important to mess with the history? You mentioned people who aren't ready to upgrade from 1.7.0 as the beneficiaries of that rewrite.  I'd rather point them at googlecode for archival tarballs.

googlecode will be up for a while longer with the full SVN history.
We'll also leave the google/googlemock repo up with its own tag history.

I don't know that there are any gmock historians who would care about the old tags. We aren't doing any maintenance on the old releases. They're not branches, and they're basically set in stone. I hope to make a v1.8.0 release very soon and make that the only supported version.

**Comment by obruns** [comment]
On Aug 29 08:49 -0700, Billy Donahue wrote:
> This is impressive work. I'm nervous about writing to the git history, though.
> Is it really important to mess with the history?

Well, I guess it depends on how much you fear the wrath of your future self.

No, seriously. The migration to Git is a once-in-a-lifetime opportunity and I like to pay as much attention to the details as possible because the result is going to be the one true repository. Yes, the Subversion repo will be around but who wants to have a peek into history with the Subversion command line tools when he could do that with their vastly superior Git counterparts?

You can keep the repository as is but that decision is permanent. Your future self may regret it but rewriting history then would break the many users that depend on your repo's history. Just think about submodule references that no longer resolve because you decided that an improved history would be nice.

I'm going to give a quick summary of my use case but in the end it depends on whether you expect others to depend on a properly migrated repository, too:

At the time we started writing tests using gmock, I told my coworkers to just take the release tarball and commit it into Subversion. Using `svn:externals` was not an option because part of the team uses `git-svn`.  I added: "By the time we migrate from Subversion to Git, gtest and gmock will probably have been migrated so that we can purge the tarball dump from history and place a Git submodule reference to that particular gmock release instead." (I said the same about the philsquared/Catch dependency we have but Catch doesn't add a transitive dependency like gmock does, so that'll be fine)


Also, I wouldn't say that we "mess with the history". To the contrary: We're fixing the mess that a one-size-fits-all migration tool has left. There's so much more beyond turning the `svn:externals` property into a Git submodule:

* fix the time stamps which are all UTC (difficult unless you can pin committers to a certain timezone each)
* rewrite all occurrences of Subversion revisions (`r[[:digit:]]{1,}`) into Git SHA-1s (applies to commit messages)
* purge accidentally committed (and possibly huge) files (not an issue here)


Do what you think is best for the project. I can come up with alternative approaches to still keep a lean Git repository (none would be as elegant as relying on a clean upstream, though).
