### ISSUE TITLE
MakeAndRegisterTestInfo never gets called when compiled with arm-brcm-linux-gnueabi-g++

### ISSUE THREAD

**Issue by otaviomacedo** [google/googletest#601]
I have a long list of tests, but when I call `RUN_ALL_TESTS()`, no test is actually run. Debugging googletest, I noticed that `MakeAndRegisterTestInfo` never gets called. If I understand it correctly, it should be called once for every test I wrote.

I am compiling it with arm-brcm-linux-gnueabi-g++. It has probably something to do with the way this compiler handles the initialization of static members. In particular, the static constant `test_info_`, created for each test. I suspect that arm-brcm-linux-gnueabi-g++ does a kind of lazy initialization of static members, that is, it initializes the static members only when the class is accessed. Since the classes generated by the macros are never accessed, `test_info_` is never initialized and no test gets registered.

Does this make sense? And is there any way around it?

**Comment by sbenzaquen** [comment]
First thing to check is whether the compilation unit is being linked into the binary. The linker can usually throw the whole CU away because it can't find anyone using it.
Assuming it is linked, the standard allows for dynamic initialization to happen lazily as you mention.
It also says that it must happen before the first ODR-use of any function or variable of that CU.
This means you only need to define something there and ODR-use it from your main() before RUN_ALL_TESTS().
This would actually fix both issues, the linker has to link the CU and the CU has to be initialized.

**Comment by dabrahams** [comment]
I got here after looking for an answer as to what trick Googletest uses to portably ensure that the tests I write are actually registered, knowing the limitations of dynamic initialization.  I take it the answer above  means, “there's no trick; most compilers just happen to run all the dynamic initializers even if nothing in the CU is ODR-used.”  Can someone confirm that nothing has changed in this regard since 2015?

Thanks!
