### ISSUE TITLE
Migrate Google Code wiki to Github

### ISSUE THREAD

**Issue by revprez** [google/googletest#609]
Not a priority, but would be nice to migrate documentation [here](https://code.google.com/p/googletest/w/list) to Github.

**Comment by BillyDonahue** [comment]
That's already been done, hasn't it?

**Comment by davidzchen** [comment]
I don't see the documentation on GitHub. There is neither a GitHub wiki set up for this repo nor a GitHub Pages site.

It would also be great to set up redirects from the old wiki if possible since many links to the old documentation on external sites are now broken; for example: http://www.ibm.com/developerworks/aix/library/au-googletestingframework.html

**Comment by shadowcomer** [comment]
Neither do I see any documentation on GitHub. And as @davidzchen already mentioned, links are broken.

Right now, I can only find very basic tutorials written by others (which contain broken links), but no reliable documentation.

**Comment by jimbeveridge** [comment]
The docs are at https://github.com/google/googletest/tree/master/googletest/docs.
There is a PR to add a link at https://github.com/google/googletest/pull/639.

**Comment by shadowcomer** [comment]
Oh, stupid me. Sorry for being so obtuse.

Thank you very much.

**Comment by maks-a** [comment]
Let me rise that issue again, because it was not easy for me to find API documentation. I was searching for how to generate xml output report. All the old links redirect me to main README.md (that does not help much in my case). I would never guess to go googletest/googletest/docs/.

Is it possible to add explicit rubric about API documentation to the main README.md?

**Comment by davidzchen** [comment]
I agree with @maks-a. The docs under `googletest/googletest/docs` are not very discoverable, and even with #639, they are not very easy to browse from the GitHub file browser.

Ideally, we should set up a [GitHub project site](https://pages.github.com/) for googletest. This basically involves creating a gh-pages branch and hosting the documentation there. GitHub supports the [Jekyll static site generator](https://help.github.com/articles/using-jekyll-with-pages/) as well.

**Comment by BillyDonahue** [comment]
I agree. I don't know quite how to do it, but let's.

**Comment by hethi** [comment]
The [top level README](https://github.com/google/googletest) is linking directly to the Google Test Primer and to the Google Mock documentation - good enough to close this issue?

**Comment by maks-a** [comment]
That's fine with me.
