### ISSUE TITLE
ASSERT_EQ doesn't support expressions with initializer list

### ISSUE THREAD

**Issue by ip** [google/googletest#634]
Example:
```c++
    using List = std::set<int>;
    List eventResult;

    // ...

    ASSERT_EQ(eventResult, List{1, 2, 3});
```
Generates these errors in Visual Studio 2015:
![gtest bug](https://cloud.githubusercontent.com/assets/1111008/11399618/968599c2-9399-11e5-9d33-542eb23a08d5.png)

However, it works if I change last two lines like this:
```c++
    auto expectedRes = List{1, 2, 3};
    ASSERT_EQ(eventResult, expectedRes);
```

It also works for some reason with 1 argument in initializer list: `List{123}`

**Comment by BillyDonahue** [comment]
This is a preprocessor limitation.
It doesn't consider {} as a grouping brace when separating a function-like
macro's arguments.

Cheap fix: You can put your expression in parens.

Harder fix: convert ASSERT_EQ to be a variadic macro with some
mild preprocessor sorcery.

**Comment by ip** [comment]
Thanks a lot for this workaround. But aren't arguments enclosed in parens inside ASSERT_EQ and other macros?

**Comment by ip** [comment]
I mean may be it can be fixed on Google Test side?

**Comment by BillyDonahue** [comment]
Maybe you aren't catching my meaning here.

According to the preprocessor, the expression:

ASSERT_EQ(eventResult, List{1, 2, 3});

Has 4 arguments:

    eventResult

    List{1

    2

    3}

I'm suggesting:


    ASSERT_EQ(eventResult, (List{1,2,3}));


The preprocessor does paren depth counting, so it would see this as
two arguments.

**Comment by sbenzaquen** [comment]
On Wed, Nov 25, 2015 at 9:45 AM, Ivan Perevezentsev <
notifications@github.com> wrote:

> Thanks a lot for this workaround.
>
The problem is that the preprocessor sees "eventResult, List{1, 2, 3}" as 4
macro arguments.
The macro takes 2 arguments, so it gives you the "too many parameters"
error.
The preprocessor understands parens but not braces. Braces are just like
any other character.

There is a way to support arbitrary expressions using .../__VAR_ARGS__, but
that only works if you have a single argument that needs that.
What you do is to use ... for the last argument instead of a regular
argument. Then something like "List{1,2,3}" would all be gathered under the
variadic argument.
The problem is that ASSERT_EQ needs two expressions, so we can only do this
hack on the second one. In this circumstance, it is better to do it to none
of them to keep the API symmetric and avoid surprises.

>

> But aren't arguments enclosed in parens inside ASSERT_EQ and other macros?
>
The parens inside the macro are usually done to prevent bad operator
precedence from happening.
Eg:

#define TIMES_TWO(x) 2*x
int PlusOneTimesTwo(int i) {
return TIMES_TWO(i+1); // Oops. This returns 2*i+1, not 2*(i+1)
}

**Comment by ip** [comment]
Ok, now I got it, thanks.

**Comment by BillyDonahue** [comment]
You can also use List({1,2,3}).
Which is just a different syntax for calling the same List constructor.
