### ISSUE TITLE
sign mismatch warnings inconsistencies between MSVC and GCC/Clang

### ISSUE THREAD

**Issue by gpakosz** [google/googletest#683]
I noticed the following gtest behavior.

On Windows, when compiling with MSVC, if you write:

```
uint32_t a = 1;
int32_t b = -1;
EXPECT_EQ(a, b);
```

You don't get any warning while GCC/Clang emits `-Wsign-compare`.

This is caused by commit 4b83461e9772cce62e84310060fe84172e9bf4ba by @zhanyong.wan that disables MSVC warning `4389` in `CmpHelperEQ`.

```
commit 4b83461e9772cce62e84310060fe84172e9bf4ba
Author: zhanyong.wan <zhanyong.wan@861a406c-534a-0410-8894-cb66d6ee9925>
Date:   Thu Jan 29 06:49:00 2009 +0000

    Fixes some warnings when compiled with MSVC at warning level 4.
```

Now, what should the proper behavior be?
1. should we see warnings when comparing signed/unsigned values with `ASSERT|EXPECT_EQ`?
   - in which case, `-Wsign-compare` should be silenced when compiling with GCC/Clang
2. should all `ASSERT|EXPECT_` macros emit warnings
   - in which case warning `4389` shouldn't be silenced in `CmpHelperEQ`
3. should sign/unsigned mismatch warnings be silenced for all `ASSERT|EXPECT_` macros? 
   - in which case both `CmpHelperEQ` and `GTEST_IMPL_CMP_HELPER_` definitions should silence warnings

I have a PR for each case mentioned above but I don't know which behavior to choose
- I think I would favor option 1.
- option 2. could be seen as a regression. 
- option 3. is dubious in the following example:
  
  ```
  uint32_t a = 1;
  int32_t b = -1;
  EXPECT_GT(a, b);
  ```

What do you think?

**Comment by gpakosz** [comment]
Anyone?

**Comment by BillyDonahue** [comment]
I don't know what to say here. It's hard to change googletest behavior in either direction. People are very picky in either direction when warnings change. If you enable a warning, some will demand that it be turned back off. If you disable a warning, some will demand that it be turned back on. 

I think these macros should emit exactly what the equivalent direct comparison would emit.

    uint32_t a = 1;
    int32_t b = -1;
    EXPECT_GT(a, b);

I don't care if this is dubious. I know it fails because 'b' is converted to uint32_t and then compared to a. But that's what the usual arithmetic conversions dictate and who is googletest to get in the way?

Disabling warnings inside googletest doesn't sound right at all, unless those warnings are side-effects that are not the user's "fault".

**Comment by gpakosz** [comment]
Since I opened this issue, I ended up in my own copy of googletest with re-enabling `C4389` (signed/unsigned mismatch) in `EXPECT_EQ`.

By re-enabling `C4389` it seems we agree disabling warnings inside googletest doesn't sound right at all. Re-enabling it restores equivalent behavior between MSVC and GCC/Clang.
