### ISSUE TITLE
No release that bundles gtest and gmock

### ISSUE THREAD

**Issue by carlcherry** [google/googletest#684]
There is a 1.7.0.tar.gz in the old googlemock repo - but even that one is not compatible with the googletest-release-1.7.0.tar.gz.  It seems to require new things added to gtest after 1.7.0.

Are there plans to build new release file that contains both gtest and gmock.

Thanks.
Carl.

**Comment by jseadragon** [comment]
I'm using 1.7.0 from googlemock and googletest, and it works for me. What errors are you seeing?

One gotcha that I've found, is that 1.7.0 requires a compiler with C++11 support. Since I'm still on gcc-4.6, I've had to manually turn off the C++11 features by passing in `-DGTEST_LANG_CXX11=0` into my compiler flags.
