### ISSUE TITLE
Mock function called in FixtureTearDown violates expectations that should have been cleared

### ISSUE THREAD

**Issue by schoolo** [google/googletest#710]
I have a fixture test case that sets an expectation for a function to be called once, then clears the expectation immediately after I expect it to be satisfied:

```
    TEST_F(TestFixture, RespondsToTestRequest)
    {
        Message test_request = GenerateTestRequestMessage();
        std::string test_request_str = test_request.GetMessageAsString();
        EXPECT_CALL(m_gw, send(_, _, _)).Times(1);
        m_session->OnData(test_request_str.size(), test_request_str.c_str(), Datetime(10));
        ASSERT_TRUE(Mock::VerifyAndClearExpectations(&m_gw));

        ASSERT_EQ(m_gw.m_sent_messages.size(), 1);

        const MessageView &last_sent = m_gw.m_sent_messages.back();
        ASSERT_EQ(last_sent.m_fields.at("34"), "1");
        ASSERT_EQ(last_sent.m_fields.at("35"), "0");
        ASSERT_EQ(last_sent.m_fields.at("112"), test_request.GetTag("112"));
    }
```

The test case fails, with the error message being that the method `send()` has been called twice.  I see it being called twice in the debugger, but the second time is in the fixture's `TearDown()` method.  I have tried calling `Mock::VerifyAndClearExpectations()` in TearDown, directly before the mock method would be called, with no difference in result.  The problem goes away when I take the function call out of  `TearDown()`

**Comment by coreykosak** [comment]
I am not having any luck reproducing your issue. My attempt is below. When I run it, it does the expected thing (issuing an "Uninteresting mock function call - returning directly" message in ```TearDown```).

Could you try taking a look at my code and either get it to fail, or, failing that, figuring out what is the essential difference between your code and mine?

```
using ::testing::Mock;
using ::testing::_;

class Foo {
public:
  virtual ~Foo() {}
  virtual void send(int, int, int) {}
};

class MockFoo : public Foo {
 public:
  MOCK_METHOD3(send, void(int, int, int));
};

class TestFixture : public ::testing::Test {
 public:
  void TearDown() {
    cout << "Inside TearDown\n";
    m_gw.send(4, 5, 6);
  }

  MockFoo m_gw;
};

TEST_F(TestFixture, Blah) {
  EXPECT_CALL(m_gw, send(_, _, _)).Times(1);
  m_gw.send(1, 2, 3);
  ASSERT_TRUE(Mock::VerifyAndClearExpectations(&m_gw));
}
```

**Comment by jjlyon** [comment]
I was having the same issue where I had a global variable, which had a method being used in a deconstructor, as well as some other places. I wanted to verify that that method was not getting called in the main workflow, but the test was failing because the tested object was being destroyed in `Teardown()` before the mocked object. The mocked object's method was thus called during `Teardown()` and `EXPECT_CALL` was still counting that call, even though that was outside the scope of the test.

Here is an example of my code, that runs and builds with the same outcome:

```
#include "gtest/gtest.h"
#include "gmock/gmock.h"

class Goo
{
public:
	Goo() = default;
	virtual ~Goo() = default;

	virtual bool DoStuff()
	{
		return true;
	}
};

class MockGoo : public Goo
{
	public:
		MOCK_METHOD0(DoStuff, bool());
};

Goo *goo = new Goo();

class Foo
{
public:
	Foo() = default;

	virtual ~Foo()
	{
		goo->DoStuff();
	}
};

class FooTest : public testing::Test
{
protected:
	MockGoo mockGoo;
	Foo     *foo;
public:
	virtual void SetUp()
	{
		goo = &mockGoo;
		foo = new Foo();
	}

	virtual void TearDown()
 	{
		delete foo;
	}

};

TEST_F(FooTest, DoesNotDoStuff)
{
	EXPECT_CALL(mockGoo, DoStuff())
		.Times(0);
}
```

Here is the fail report:

```
Test Name:	FooTest.DoesNotDoStuff
Test FullName:	FooTest.DoesNotDoStuff
Test Source:	c:\...\testtest\testtest.cpp : line 55
Test Outcome:	Failed
Test Duration:	0:00:00

Result Message:	c:\...\testtest\testtest.cpp:56
Mock function called more times than expected - returning default value.
    Function call: DoStuff()
          Returns: false
         Expected: to be never called
           Actual: called once - over-saturated and active
```

**Comment by coreykosak** [comment]
@jjlyon I don't see that your code is materially different from my example. Specifically if you were to put  ```ASSERT_TRUE(Mock::VerifyAndClearExpectations(foo));``` prior to your call to ```delete foo``` you would get the same "Uninteresting mock function call" message that I did.

**Comment by dbuccier** [comment]
@coreykosak I think the problem is not "we can't find a workaround to the bug," more than it is "this is fundamentally opposite of what every testing framework has ever done."

Is there ever a feasible point in time where we would want things in the teardown accepted as part of a test?  That defeats the purpose of splitting up the two concepts and breaks the principles of unit testing.

While we're glad that there is a workaround, this is something that should be changed in the framework to meet the expectation that code should follow the model of least surprise.  Either that, or there needs to be significantly clearer documentation that mocks are still active through teardown unless manually cleared.

**Comment by coreykosak** [comment]
@dbuccier, that was not the original poster's question. You are welcome to create a feature request (or submit a patch) if you want the owners to consider the change you suggest.

**Comment by dbuccier** [comment]
We posted here because we felt like fixing the issue we pointed out would resolve the original poster's concern as well.  We will create a separate issue though.
