### ISSUE TITLE
googlecode tarballs 404; Github releases require autoconf

### ISSUE THREAD

**Issue by jfirebaugh** [google/googletest#901]
It appears that previously-available tarballs on googlecode.com, e.g. https://googletest.googlecode.com/files/gtest-1.7.0.zip, have been pulled. The [Github releases](https://github.com/google/googletest/releases) appear to be different packages, and notably, they require autoconf -- no `configure` file is present.

Is this intentional? Both the fact that prior tarball URLs now 404 and now the lack of `configure` are inconvenient for downstream packagers.

**Comment by georgen117** [comment]
I think that removal of the configure file is intentional.  from the gtest-1.7.0 README file

> ### Upgrading from 1.4.0 or Earlier ###
>
> The Autotools build script (configure + make) is no longer officially
> supportted.  You are encouraged to migrate to your own build system or
> use CMake.  If you still need to use Autotools, you can find
> instructions in the README file from Google Test 1.4.0.

I looks to me like google test has been trying to move away from the configure file for quite some time

I was able to use the configure.ac file to generate a new configure file using the following steps.  (some steps may not be needed.)

    autoupdate # used to update the outdated configure.ac 
    libtoolize --force
    aclocal
    autoheader
    automake --force-missing --add-missing
    autoconf

Due to the fact that the code base is clearly moving away from autoconf tools I am updating all my scripts that used the configure to no longer use configure.
(I am not a gtest developer just a user)
