### ISSUE TITLE
Ctest & Google Test/Mock

### ISSUE THREAD

**Issue by agirault** [google/googletest#916]
Is there any support to facilitate running google tests with CTest? Has anyone attempted to do it?
See CMake `add_test`: https://cmake.org/cmake/help/v3.0/command/add_test.html

To make its integration easier, It would be nice to be able to configure a subset of tests to run in C++, like the flag `gtest_filter` allows to do in command line (https://github.com/google/googletest/blob/master/googletest/docs/AdvancedGuide.md#running-a-subset-of-the-tests).

**Comment by agirault** [comment]
After some searching, I'll share what I found. Could be useful to add to gtest doc?

CMake offers a couple functions to find google-test and add ctests running google-tests:
https://cmake.org/cmake/help/v3.5/module/FindGTest.html

**Comment by fengyuruhui** [comment]
I have another problem when using CTEST+googl-test with cmake gtest_add_tests():
CTEST will run global test environment set-up, per-test-case set-up , per-test SetUp  for each case, the behavior is the same as  using --gtest_filter for each case. This would be OK when run single case , but when we run a case list with CTEST, that would NOT  be the real behavior we want, and the behavior is totally different with google-test.  Is there anyway to avoid this? Thanks in advance!

**Comment by mwoehlke-kitware** [comment]
> CTEST will run global test environment set-up, per-test-case set-up , per-test SetUp for each case, the behavior is the same as using --gtest_filter for each case.

The behavior isn't "the same as using --gtest_filter".... it *is* using `--gtest_filter`. This is not avoidable; each CTest test is a separate invocation of the test executable. (And this is a Good Thing; if one CTest test crashes, it won't affect any others.) The only way to avoid this (and not lose granularity) would be if CTest parsed an output file generated by the test executable in order to sort out results for multiple "tests". I'm not aware that CTest supports any such mechanism at this time.

> Is there anyway to avoid this?

Use `add_test` instead. However, you will only have one CTest test this way, which runs *all* your tests (in that executable) and only (unless you use `ctest -V` to see the verbose test output) reports if the whole thing passed.

**Comment by mwoehlke-kitware** [comment]
CMake 3.10 introduced a new [dynamic discovery](https://blog.kitware.com/dynamic-google-test-discovery-in-cmake-3-10/) that may be preferred over `gtest_add_tests`. If the documentation is updated, I would encourage mentioning that instead or in addition.

**Comment by johnb003** [comment]
CMake 3.9 has added GoogleTest support:
https://cmake.org/cmake/help/v3.9/module/GoogleTest.html?highlight=google%20test#command:gtest_add_tests

I've also built an example about downloading gtest on demand, and configuring the library:
https://gist.github.com/johnb003/65982fdc7a1274fdb023b0c68664ebe4

**Comment by mwoehlke-kitware** [comment]
> CMake 3.9 has added GoogleTest support

That wasn't "added" in 3.9; it's been around much longer, albeit as part of [`FindGTest`](https://cmake.org/cmake/help/v3.8/module/FindGTest.html). It was refactored into a separate "use" file in 3.9.

**Comment by gennadiycivil** [comment]
I have been cleaning up older and inactive GitHub googletest issues. You may see an issue "closed" if it appears to be inactive/abandoned 
Thank you
