### ISSUE TITLE
Memory leaks reported by Visual Studio's heap checker

### ISSUE THREAD

**Issue by jdukat** [google/googletest#970]
Hi,
When heap checking is enabled as explained in this article:
[](https://msdn.microsoft.com/en-us/library/x98tx3cf.aspx)

I get several (~10) heap leaks caused by gtest code.
Stack traces on allocation breakpoints are quite complex and may be specific to my code, so for now just the question: is anyone else experiencing this also? Maybe a known issue?

**Comment by ynikanchyk** [comment]
Vote for "yes, it's a known issue". Take a look on https://github.com/google/googletest/pull/892, it has some more references. Or, just use this for actual state : https://github.com/google/googletest/issues?utf8=✓&q=is%3Aissue%20is%3Aopen%20memory%20leak .

As for me, the workaround at https://github.com/google/googletest/pull/757 doesn't work (crashes probably because of wrong order of statics destruction), and https://github.com/google/googletest/pull/892 seems to be ok (but can't see if this PR is a real reason of failed checks at https://ci.appveyor.com/project/BillyDonahue/googletest/build/83, seems it's not).

**Comment by gennadiycivil** [comment]
Should be addressed by #1142
